// Generated by `cargo xtask generate typescript` from crates/catchlight-editor-protocol.
// Do not edit: run `cargo xtask generate` and commit the result. CI fails on drift.

/**
 * One open editing session (one model and its undo history). Opaque: a
 * session is not part of any model, so it has no Id of its own.
 */
export type SessionId = number;

/**
 * The identity of a node. Unique within a model; generated as `<parent id>/<kind>-<8 hex>` by [`NodeId::generate`].
 */
export type NodeId = string;

/**
 * The identity of a param. Unique within a model; generated as `param-<8 hex>` by [`ParamId::generate`].
 */
export type ParamId = string;

/**
 * The identity of a texture. Unique within a model; generated as `tex-<8 hex>` by [`TexId::generate`].
 */
export type TexId = string;

/**
 * The identity of a slot, unique within the part that owns it — not within the model. Generated as `slot-<8 hex>` by [`SlotId::generate`].
 */
export type SlotId = string;

export type Command =
  | {
    "cmd": "session_new",
    name: string | null,
  }
  | {
    "cmd": "session_open",
    path: string,
  }
  | {
    "cmd": "session_list"
  }
  | {
    "cmd": "session_close",
    session: SessionId,
  }
  | {
    "cmd": "save",
    session: SessionId,
    path: string | null,
  }
  | {
    "cmd": "export_manifest",
    session: SessionId,
    path: string,
  }
  | {
    "cmd": "status",
    session: SessionId,
  }
  | {
    "cmd": "check",
    session: SessionId,
  }
  | {
    "cmd": "node_tree",
    session: SessionId,
  }
  | {
    "cmd": "node_info",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "node_add",
    session: SessionId,
    parent: NodeId,
    kind: NodeKindArg,
    name: string | null,
    /**
     * The Id to create it under. Absent generates one; an Id the model
     * already carries is [`ErrorCode::DuplicateId`].
     */
    node?: NodeId | null,
  }
  | {
    "cmd": "node_set",
    session: SessionId,
    node: NodeId,
    /**
     * The label a person reads. Free to repeat; nothing is addressed by it.
     */
    name?: string | null,
    translate?: [number, number, number] | null,
    rotate?: [number, number, number] | null,
    scale?: [number, number] | null,
    z_order?: number | null,
    opacity?: number | null,
    enabled?: boolean | null,
    /**
     * The texture the part draws, in three states: absent leaves it as it
     * is, `null` draws none, an Id draws that one. Ignored on a node that is
     * not a part. Dropping the last part drawing a texture takes the texture
     * with it — see [`ResponseBody::Node::dropped`].
     */
    texture?: TexId | null,
    lock_to_root?: boolean | null,
    blend_mode?: BlendMode | null,
    tint?: [number, number, number] | null,
    screen_tint?: [number, number, number] | null,
    mask_threshold?: number | null,
    /**
     * Composite: forward mesh-group deformation to children.
     */
    propagate_meshgroup?: boolean | null,
    mg_translate_children?: boolean | null,
  }
  | {
    "cmd": "node_reparent",
    session: SessionId,
    node: NodeId,
    to: NodeId,
  }
  | {
    "cmd": "node_reorder",
    session: SessionId,
    node: NodeId,
    index: number,
  }
  | {
    "cmd": "node_move",
    session: SessionId,
    node: NodeId,
    parent: NodeId,
    index: number,
  }
  | {
    "cmd": "node_duplicate",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "rename_id",
    session: SessionId,
    rename: Rename,
  }
  | {
    "cmd": "mask_add",
    session: SessionId,
    node: NodeId,
    source: NodeId,
    mode: MaskMode,
  }
  | {
    "cmd": "mask_set",
    session: SessionId,
    node: NodeId,
    index: number,
    mode: MaskMode,
  }
  | {
    "cmd": "mask_reorder",
    session: SessionId,
    node: NodeId,
    index: number,
    to: number,
  }
  | {
    "cmd": "mask_delete",
    session: SessionId,
    node: NodeId,
    index: number,
  }
  | {
    "cmd": "physics_set",
    session: SessionId,
    node: NodeId,
    kind: PhysicsKind | null,
    map_mode: PhysicsMapMode | null,
    local_only: boolean | null,
    /**
     * The params the driver writes ([`PhysicsTargets`]). Absent leaves
     * both outputs as they are; present, both become exactly what it
     * says, so `{}` detaches both and `{"length": "len"}` binds the
     * second output and unbinds the first.
     */
    target_params: PhysicsTargets | null,
    gravity: number | null,
    length: number | null,
    frequency: number | null,
    angle_damping: number | null,
    length_damping: number | null,
    output_scale: [number, number] | null,
  }
  | {
    "cmd": "physics_globals",
    session: SessionId,
    gravity: number | null,
    pixels_per_meter: number | null,
  }
  | {
    "cmd": "node_delete",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "texture_add",
    session: SessionId,
    node: NodeId,
    /**
     * How to read the attached bytes. The field, never a sniff.
     */
    encoding: TextureEncoding,
    /**
     * The Id to create it under. Absent generates one; an Id the model
     * already carries is [`ErrorCode::DuplicateId`].
     */
    texture?: TexId | null,
  }
  | {
    "cmd": "texture_list",
    session: SessionId,
  }
  | {
    "cmd": "param_add",
    session: SessionId,
    name: string,
    min: number,
    max: number,
    default: number,
    key_positions: Array<number>,
    /**
     * The Id to create it under. Absent generates one; an Id the model
     * already carries is [`ErrorCode::DuplicateId`].
     */
    param?: ParamId | null,
  }
  | {
    "cmd": "param_list",
    session: SessionId,
  }
  | {
    "cmd": "param_set",
    session: SessionId,
    param: ParamId,
    name: string | null,
    min: number | null,
    max: number | null,
    default: number | null,
  }
  | {
    "cmd": "param_delete",
    session: SessionId,
    param: ParamId,
  }
  | {
    "cmd": "param_key_insert",
    session: SessionId,
    param: ParamId,
    value: number,
  }
  | {
    "cmd": "param_key_delete",
    session: SessionId,
    param: ParamId,
    index: number,
  }
  | {
    "cmd": "param_key_move",
    session: SessionId,
    param: ParamId,
    index: number,
    value: number,
  }
  | {
    "cmd": "param_flip",
    session: SessionId,
    param: ParamId,
  }
  | {
    "cmd": "binding_add",
    session: SessionId,
    node: NodeId,
    target: ScalarTarget,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_key",
    session: SessionId,
    node: NodeId,
    target: ScalarTarget,
    /**
     * `[x, y]` index into the binding's key grid; `y` is 0 for a
     * one-param binding.
     */
    cell: [number, number],
    value: number,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_keys",
    session: SessionId,
    node: NodeId,
    cell: [number, number],
    entries: Array<BindingKeyEntry>,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_unset",
    session: SessionId,
    node: NodeId,
    target: BindingTarget,
    cell: [number, number],
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_reset",
    session: SessionId,
    node: NodeId,
    target: BindingTarget,
    cell: [number, number],
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_delete",
    session: SessionId,
    node: NodeId,
    target: BindingTarget,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_interpolate",
    session: SessionId,
    node: NodeId,
    target: BindingTarget,
    mode: Interpolate,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_invert",
    session: SessionId,
    node: NodeId,
    target: BindingTarget,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_copy_key",
    session: SessionId,
    node: NodeId,
    target: BindingTarget,
    from: [number, number],
    to: [number, number],
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_list",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "deform_set",
    session: SessionId,
    node: NodeId,
    cell: [number, number],
    translate: [number, number] | null,
    rotate: number | null,
    scale: [number, number] | null,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "deform_vertices",
    session: SessionId,
    node: NodeId,
    cell: [number, number],
    offsets: Array<[number, number]>,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "mesh_set",
    session: SessionId,
    node: NodeId,
    /**
     * One `[x, y]` per vertex.
     */
    verts: Array<[number, number]>,
    /**
     * One `[u, v]` per vertex, as many as `verts`.
     */
    uvs: Array<[number, number]>,
    /**
     * One `[a, b, c]` per triangle, each a `verts` index.
     */
    indices: Array<[number, number, number]>,
    origin: [number, number],
  }
  | {
    "cmd": "mesh_auto",
    session: SessionId,
    node: NodeId,
    /**
     * Absent is [`AutoMesh::Contour`] with every knob at its default.
     */
    mode: AutoMesh,
  }
  | {
    "cmd": "mesh_copy",
    session: SessionId,
    from: NodeId,
    to: NodeId,
  }
  | {
    "cmd": "slot_add",
    session: SessionId,
    node: NodeId,
    /**
     * Absent generates one (`slot-<8 hex>`, re-drawn until it is free on
     * the part). The reply names it either way.
     */
    slot?: SlotId | null,
  }
  | {
    "cmd": "slot_fill",
    session: SessionId,
    node: NodeId,
    slot: SlotId,
    vertex: number,
  }
  | {
    "cmd": "slot_clear",
    session: SessionId,
    node: NodeId,
    slot: SlotId,
  }
  | {
    "cmd": "slot_delete",
    session: SessionId,
    node: NodeId,
    slot: SlotId,
  }
  | {
    "cmd": "slots",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "welds",
    session: SessionId,
  }
  | {
    "cmd": "unfilled_slots",
    session: SessionId,
  }
  | {
    "cmd": "weld_weight",
    session: SessionId,
    a: NodeId,
    b: NodeId,
    slot: SlotId,
    weight: number,
  }
  | {
    "cmd": "weld_set",
    session: SessionId,
    a: NodeId,
    b: NodeId,
    pairs: Array<SlotPair>,
  }
  | {
    "cmd": "weld_delete",
    session: SessionId,
    a: NodeId,
    b: NodeId,
  }
  | {
    "cmd": "physics_add",
    session: SessionId,
    parent: NodeId,
    name: string | null,
    kind: PhysicsKind,
    /**
     * The params the driver writes ([`PhysicsTargets`]). Absent binds
     * neither output.
     */
    target_params: PhysicsTargets,
    length: number | null,
    gravity: number | null,
    frequency: number | null,
    angle_damping: number | null,
    length_damping: number | null,
    /**
     * The Id to create it under. Absent generates one; an Id the model
     * already carries is [`ErrorCode::DuplicateId`].
     */
    node?: NodeId | null,
  }
  | {
    "cmd": "undo",
    session: SessionId,
  }
  | {
    "cmd": "redo",
    session: SessionId,
  }
  | {
    "cmd": "presence_set",
    session: SessionId,
    pose: Array<ParamPose>,
    camera?: Camera | null,
    selection?: NodeId | null,
  }
  | {
    "cmd": "presence_get",
    session: SessionId,
  }
  | {
    "cmd": "scratch_deform",
    session: SessionId,
    node: NodeId,
    offsets: Array<[number, number]>,
  }
  | {
    "cmd": "preview",
    session: SessionId,
    pose: Array<ParamPose>,
    size: [number, number] | null,
    camera: Camera | null,
  }
  | {
    "cmd": "import_file",
    session: SessionId,
    parent?: NodeId | null,
  }
  | {
    "cmd": "import_json",
    session: SessionId,
    parent?: NodeId | null,
    /**
     * Every texture the attachments carry, in any order.
     */
    textures: Array<ImportTexture>,
  }
  | {
    "cmd": "extension_set",
    session: SessionId,
    key: ExtensionKey,
    value: ExtensionSet,
  }
  | {
    "cmd": "extension_delete",
    session: SessionId,
    key: ExtensionKey,
  }
  | {
    "cmd": "extensions",
    session: SessionId,
  }
  | {
    "cmd": "extension_get",
    session: SessionId,
    key: ExtensionKey,
  }
  | {
    "cmd": "import_manifest",
    session: SessionId,
  };

export type NodeKindArg =
  | "group"
  | "part"
  | "composite"
  | "mesh_group";

/**
 * What a node is, as a reply reports it. [`NodeKindArg`] is the add side and
 * carries no `Physics`: [`Command::PhysicsAdd`] is what makes one.
 */
export type NodeKind =
  | "group"
  | "part"
  | "composite"
  | "mesh_group"
  | "physics";

/**
 * What a mask source does to the drawable it is attached to.
 */
export type MaskMode =
  | "mask"
  | "dodge";

/**
 * The pendulum a physics driver swings.
 */
export type PhysicsKind =
  | "rigid"
  | "spring";

/**
 * What a physics driver's two outputs mean; see [`PhysicsTargets`].
 */
export type PhysicsMapMode =
  | "xy"
  | "yx"
  | "angle_length"
  | "length_angle";

/**
 * How a binding reads between the cells its author keyed.
 */
export type Interpolate =
  | "nearest"
  | "stepped"
  | "linear"
  | "cubic";

/**
 * How a drawable composites onto what is already under it.
 */
export type BlendMode =
  | "normal"
  | "multiply"
  | "color_dodge"
  | "linear_dodge"
  | "screen"
  | "clip_to_lower"
  | "slice_from_lower"
  | "overlay"
  | "color_burn"
  | "linear_burn"
  | "darken"
  | "lighten"
  | "add"
  | "inverse"
  | "subtract";

/**
 * How to read a texture's bytes. The field a command carries beside its
 * image, so nothing has to guess from a file name.
 */
export type TextureEncoding =
  | "png"
  | "tga";

/**
 * What a texture's stored bytes mean by their alpha channel.
 *
 * The bytes cannot say, so the command carrying them does. Straight is the
 * default because it is what an editor writes and what every PNG a person
 * exports holds; `.inx` textures are the premultiplied ones.
 */
export type TextureAlpha =
  | "straight"
  | "premultiplied_srgb";

/**
 * A property a binding drives with one number per cell.
 *
 * The spellings are the model file's own, which is why the colour and
 * output-scale channels run their words together rather than reading as
 * snake_case.
 */
export type ScalarTarget =
  | "tx"
  | "ty"
  | "sx"
  | "sy"
  | "rx"
  | "ry"
  | "rz"
  | "z_order"
  | "opacity"
  | "tintr"
  | "tintg"
  | "tintb"
  | "screentintr"
  | "screentintg"
  | "screentintb"
  | "outputscalex"
  | "outputscaley";

/**
 * Any property a binding drives: one of [`ScalarTarget`]'s scalars, or the
 * per-vertex deform, which the deform commands author instead.
 */
export type BindingTarget =
  | "tx"
  | "ty"
  | "sx"
  | "sy"
  | "rx"
  | "ry"
  | "rz"
  | "z_order"
  | "opacity"
  | "tintr"
  | "tintg"
  | "tintb"
  | "screentintr"
  | "screentintg"
  | "screentintb"
  | "outputscalex"
  | "outputscaley"
  | "deform";

/**
 * Fields to change on a node; every field is optional (absent = unchanged).
 * Kind-specific fields are ignored on nodes of another kind: the colour fields
 * (`opacity`, `blend_mode`, `tint`, `screen_tint`) reach parts and composites
 * only, because a mesh group is never drawn and carries no colour.
 */
export type NodePatch = {
  /**
   * The label a person reads. Free to repeat; nothing is addressed by it.
   */
  name?: string | null,
  translate?: [number, number, number] | null,
  rotate?: [number, number, number] | null,
  scale?: [number, number] | null,
  z_order?: number | null,
  opacity?: number | null,
  enabled?: boolean | null,
  /**
   * The texture the part draws, in three states: absent leaves it as it
   * is, `null` draws none, an Id draws that one. Ignored on a node that is
   * not a part. Dropping the last part drawing a texture takes the texture
   * with it — see [`ResponseBody::Node::dropped`].
   */
  texture?: TexId | null,
  lock_to_root?: boolean | null,
  blend_mode?: BlendMode | null,
  tint?: [number, number, number] | null,
  screen_tint?: [number, number, number] | null,
  mask_threshold?: number | null,
  /**
   * Composite: forward mesh-group deformation to children.
   */
  propagate_meshgroup?: boolean | null,
  mg_translate_children?: boolean | null,
};

/**
 * The params a physics driver writes, one field per output.
 *
 * A driver has exactly two outputs and never a third, so this is a struct
 * rather than a list: there is no way to name an output that does not exist,
 * and no positional hole to spell with a `null`. An absent field is an output
 * bound to nothing, so `{"length": "len"}` is a driver whose second output
 * drives a param and whose first drives none, and `{}` is a driver that
 * writes nothing.
 *
 * The names are the outputs under the `angle_length` map mode. Another map
 * mode changes what each output *means* — `length_angle` swaps them, `xy` and
 * `yx` make them a position — never how many there are.
 */
export type PhysicsTargets = {
  /**
   * The param the driver's first output writes.
   */
  angle?: ParamId | null,
  /**
   * The param the driver's second output writes.
   */
  length?: ParamId | null,
};

/**
 * How [`Command::MeshAuto`] derives a mesh from a part's alpha.
 *
 * **Every knob is optional, and none of the defaults are written here.** They
 * live in `catchlight-editor-core` beside the code that reads them, so the
 * wire cannot drift from what the editor actually does; absent means "what
 * the editor would have used". `{"mode": "contour"}` is the default trace.
 */
export type AutoMesh =
  | {
    "mode": "contour",
    /**
     * Alpha strictly above this counts as solid.
     */
    threshold?: number | null,
    /**
     * Douglas-Peucker tolerance, in texels: higher is a coarser outline.
     */
    simplify?: number | null,
    /**
     * Texels of outward dilation before tracing, so the outline clears
     * the art's own edge.
     */
    margin?: number | null,
    /**
     * Interior fill-point spacing in texels; 0 is boundary only.
     */
    spacing?: number | null,
    /**
     * One ring of free vertices per factor, the traced outline scaled
     * about its own centroid: 0 is the centroid itself, 1 the outline.
     * A factor above 1 is clamped to 1 — `margin` already dilates the
     * mask before tracing, and a vertex outside the pinned loop would
     * only make triangles the alpha cull drops. Empty places no rings,
     * which is the default.
     */
    rings?: Array<number> | null,
    /**
     * Texels: a free vertex closer than this to one already placed is
     * dropped, so rings and fill do not crowd the outline. The pinned
     * outline itself is never thinned.
     */
    min_distance?: number | null,
    /**
     * Texel x of a vertical mirror line: free vertices are generated
     * from `x <= mirror_x` and reflected across it, so a symmetric part
     * gets a symmetric interior. The outline is traced from the alpha
     * and is not mirrored.
     */
    mirror_x?: number | null,
  }
  | {
    "mode": "grid",
    /**
     * Alpha strictly above this counts as solid, and is what the
     * bounding box is measured from.
     */
    threshold?: number | null,
    cols?: number | null,
    rows?: number | null,
    /**
     * Grid lines as fractions of the solid bounding box — 0 its left
     * edge, 1 its right — so the grid need not be uniform. Values
     * outside `0..=1` put a line outside the box. Present, it replaces
     * both `cols` and `margin` on this axis. A grid is mirrored by
     * asking for symmetric fractions, which is why there is no mirror
     * knob here.
     */
    axes_x?: Array<number> | null,
    /**
     * The same, down, replacing `rows`.
     */
    axes_y?: Array<number> | null,
    /**
     * Fraction of the bounding box added outside it on both sides, when
     * the lines come from `cols`/`rows`.
     */
    margin?: number | null,
  };

/**
 * Which Id [`Command::RenameId`] changes, and to what.
 */
export type Rename =
  | {
    "kind": "node",
    from: NodeId,
    to: NodeId,
  }
  | {
    "kind": "param",
    from: ParamId,
    to: ParamId,
  }
  | {
    "kind": "texture",
    from: TexId,
    to: TexId,
  }
  | {
    "kind": "slot",
    node: NodeId,
    from: SlotId,
    to: SlotId,
  };

/**
 * The param, or the pair of params, a binding is keyed by. With `param_y`
 * the binding's grid spans both params' key positions and `cell` indexes
 * both; without it the grid is one row and `cell[1]` is 0.
 */
export type BindingParams = {
  param: ParamId,
  param_y?: ParamId | null,
};

export type BindingKeyEntry = {
  target: ScalarTarget,
  value: number,
};

/**
 * One param at one value — a pose is a list of these. Params are scalar, so
 * there is one number.
 */
export type ParamPose = {
  param: ParamId,
  value: number,
};

/**
 * One texture an [`Command::ImportJson`] structure names, and how to read the
 * bytes that came with it.
 *
 * The bytes arrive as attachment `texture:<texture>`. Encoding and alpha are
 * fields rather than a sniff or a file-name tail, because a JSON structure
 * names no files: the client that has the image is the only thing that knows
 * what it holds.
 */
export type ImportTexture = {
  texture: TexId,
  encoding: TextureEncoding,
  alpha: TextureAlpha,
};

/**
 * One slot of a model, named in full: a [`SlotId`] is unique within its part,
 * so it travels beside the node carrying it.
 */
export type SlotAddr = {
  node: NodeId,
  slot: SlotId,
};

/**
 * One pair a weld holds: a slot on its `a` part, a slot on its `b` part, and
 * `a`'s share of the point the two vertices are pulled toward.
 */
export type SlotPair = {
  a: SlotId,
  b: SlotId,
  weight: number,
};

/**
 * Ephemeral shared view state. Rides its own path — decoupled from the model
 * so scrubbing/panning generate zero edit traffic and never persist.
 */
export type Presence = {
  pose: Array<ParamPose>,
  camera?: Camera | null,
  selection?: NodeId | null,
};

export type Camera = {
  center: [number, number],
  height: number,
};

/**
 * The key an extension is filed under: the Id charset plus a required
 * interior dot, vendor first (`molan.caster`).
 *
 * Hand-written rather than one of the [`string_id!`] types because it is the
 * one Id-shaped string with a rule of its own ([`validate_extension_key`]),
 * and because a key that fails on the way in is worth naming in the error —
 * a file names its extensions in one flat map, so "which key" is the whole
 * question.
 */
export type ExtensionKey = string;

/**
 * What [`Command::ExtensionSet`] is setting: a JSON value inline, or bytes
 * that arrive as the `value` attachment.
 *
 * Tagged by `kind` rather than sniffed, because a byte extension's own
 * marker is a JSON object and an untagged value could not tell the two
 * apart. `kind: "bytes"` carries no value here — the bytes are attached —
 * and an attachment on a `json` set is refused, so exactly one of the two
 * says what the value is.
 */
export type ExtensionSet =
  | {
    "kind": "json",
    /**
     * Whatever JSON the vendor wrote. Nothing here reads it.
     */
    value: unknown,
  }
  | {
    "kind": "bytes"
  };

/**
 * What an extension holds, as a reply reports it.
 *
 * A JSON value travels whole; bytes travel as the size and hash their marker
 * carries, which is what a client compares to decide whether to fetch them.
 * The bytes themselves come back as [`Command::ExtensionGet`]'s payload.
 */
export type ExtensionValueInfo =
  | {
    "kind": "json",
    /**
     * Whatever JSON the vendor wrote. Nothing here reads it.
     */
    value: unknown,
  }
  | {
    "kind": "bytes",
    size: number,
    /**
     * Lowercase hex of the content hash the marker carries.
     */
    hash: string,
  };

/**
 * One extension, as [`Command::Extensions`] lists it.
 */
export type ExtensionInfo = {
  key: ExtensionKey,
  value: ExtensionValueInfo,
};

/**
 * The server's answer. `Ok`/`Err` carry the request's `id`; `Event` is
 * unsolicited (a model changed on a session this client observes).
 */
export type Reply =
  | {
    "reply": "ok",
    id: number,
    /**
     * The addressed session's revision *after* this command, so a client
     * knows what its reply describes without a second round trip.
     *
     * Present whenever the command named a session — including one it
     * only read, and including the create/open/import commands, which
     * report the revision of the session they just made. Absent for the
     * editor-level commands that name no session at all, and for a
     * `session_close`, whose session is gone.
     */
    rev?: number | null,
    body: ResponseBody,
  }
  | {
    "reply": "err",
    id: number,
    code: ErrorCode,
    message: string,
  }
  | {
    "reply": "event"
  } & Event;

/**
 * Why a command was refused. A client that has to react — a commit gate
 * waiting on unfilled slots, a mesh editor offering to refill a slot —
 * branches on this rather than on the message text.
 */
export type ErrorCode =
  | "no_session"
  | "no_node"
  | "no_param"
  | "no_texture"
  | "bad_request"
  | "bad_target"
  | "nothing_to_undo"
  | "nothing_to_redo"
  | "no_save_path"
  | "unknown_slot"
  | "duplicate_id"
  | "duplicate_slot"
  | "weld_unknown_slot"
  | "weld_slot_paired_twice"
  | "bad_weld_end"
  | "duplicate_weld"
  | "weld_weight_out_of_range"
  | "unknown_weld"
  | "nothing_to_mesh"
  | "fragment"
  | "edit"
  | "manifest"
  | "io"
  | "image"
  | "preview"
  | "native_only"
  | "bulk_over_http"
  | "not_empty"
  | "no_extension"
  | "reserved_extension";

export type ResponseBody =
  | {
    "result": "empty"
  }
  | {
    "result": "session",
    session: SessionId,
  }
  | {
    "result": "sessions",
    sessions: Array<SessionInfo>,
  }
  | {
    "result": "node",
    node: NodeId,
    /**
     * Textures the edit deleted, because no part draws them any more.
     * Every texture a model carries is drawn by a part, so repointing or
     * removing the last one takes the texture with it.
     */
    dropped?: Array<TexId>,
  }
  | {
    "result": "param",
    param: ParamId,
  }
  | {
    "result": "slot",
    slot: SlotAddr,
  }
  | {
    "result": "params",
    params: Array<ParamInfo>,
  }
  | {
    "result": "bindings",
    bindings: Array<BindingInfo>,
  }
  | {
    "result": "texture",
    texture: TexId,
    /**
     * Textures the edit deleted, because the part that had been drawing
     * them stopped and nothing else was. Every texture a model carries
     * is drawn by a part, so an upload that displaces the last user of
     * the old one takes it.
     */
    dropped?: Array<TexId>,
  }
  | {
    "result": "textures",
    textures: Array<TexInfo>,
  }
  | {
    "result": "tree",
    root: TreeNode,
  }
  | {
    "result": "node_info",
    node: NodeInfo,
  }
  | {
    "result": "status",
    status: StatusInfo,
  }
  | {
    "result": "warnings",
    warnings: Array<string>,
  }
  | {
    "result": "preview",
    preview: PreviewInfo,
  }
  | {
    "result": "saved",
    path: string,
  }
  | {
    "result": "presence",
    presence: Presence | null,
  }
  | {
    "result": "slots",
    slots: Array<SlotInfo>,
  }
  | {
    "result": "welds",
    welds: Array<WeldInfo>,
  }
  | {
    "result": "unfilled_slots",
    slots: Array<SlotAddr>,
  }
  | {
    "result": "emptied",
    node: NodeId,
    slots: Array<SlotId>,
  }
  | {
    "result": "extensions",
    extensions: Array<ExtensionInfo>,
  }
  | {
    "result": "extension",
    key: ExtensionKey,
    value: ExtensionValueInfo,
  };

export type Event =
  | {
    "event": "model_changed",
    session: SessionId,
    rev: number,
  }
  | {
    "event": "sessions_changed"
  };

export type SessionInfo = {
  session: SessionId,
  title: string,
  file: string | null,
  dirty: boolean,
  rev: number,
  node_count: number,
};

export type StatusInfo = {
  title: string,
  node_count: number,
  param_count: number,
  texture_count: number,
  dirty: boolean,
  rev: number,
};

export type TreeNode = {
  /**
   * What the node is addressed by, here and in the file.
   */
  id: NodeId,
  /**
   * What a person reads. Free to repeat.
   */
  name: string,
  kind: NodeKind,
  z_order: number,
  enabled: boolean,
  children: Array<TreeNode>,
};

/**
 * One node in full: what [`NodePatch`] can set, plus what it cannot — the
 * node's Id, its kind, its parent, and the size of the mesh it holds.
 *
 * **The settable fields carry [`NodePatch`]'s own names.** An inspector reads
 * a value here, edits it, and sends it straight back in a
 * [`Command::NodeSet`] under the same key; a field that spelled itself
 * differently on the way out would be a rename nothing checks.
 *
 * A field a node's kind does not carry is absent, the way it is ignored on
 * the way in: the colour fields reach parts and composites only, `texture`
 * only a part, `mg_*` only a mesh group, and the two mesh counts only the
 * kinds that hold a mesh. `texture` is also absent on a part that draws
 * none, which `kind` tells apart from a node that could not have one — a
 * reply has nothing to undo, so it never carries the `null` a patch spells
 * "draw none" with.
 */
export type NodeInfo = {
  /**
   * What the node is addressed by, here and in the file.
   */
  id: NodeId,
  /**
   * The same kind [`TreeNode::kind`] carries.
   */
  kind: NodeKind,
  /**
   * Absent on the root, which is the one node with no parent.
   */
  parent?: NodeId | null,
  /**
   * What a person reads. Free to repeat; nothing is addressed by it.
   */
  name: string,
  translate: [number, number, number],
  rotate: [number, number, number],
  scale: [number, number],
  z_order: number,
  enabled: boolean,
  lock_to_root: boolean,
  opacity?: number | null,
  blend_mode?: BlendMode | null,
  tint?: [number, number, number] | null,
  screen_tint?: [number, number, number] | null,
  mask_threshold?: number | null,
  /**
   * The part's albedo texture, absent when it draws none.
   */
  texture?: TexId | null,
  /**
   * How many vertices the node's mesh holds. Absent on a kind that carries
   * no mesh — a part and a mesh group carry one, nothing else does — so
   * `0` is a mesh with no vertices rather than a node that could not have
   * had any. A client asking "has this part been meshed" reads this rather
   * than [`Command::Check`], whose textured-but-untriangulated warning is a
   * message for a person.
   */
  vertex_count?: number | null,
  /**
   * How many triangles that mesh holds, absent under the same rule.
   */
  triangle_count?: number | null,
  /**
   * Composite: forward mesh-group deformation to children.
   */
  propagate_meshgroup?: boolean | null,
  mg_translate_children?: boolean | null,
};

export type TexInfo = {
  id: TexId,
  width: number,
  height: number,
};

export type ParamInfo = {
  /**
   * What the param is addressed by.
   */
  id: ParamId,
  /**
   * What a person reads. Free to repeat.
   */
  name: string,
  min: number,
  max: number,
  default: number,
  /**
   * Key positions, normalized 0..1 across `[min, max]`. Always at least
   * the two endpoints, so a binding's grid is `key_positions.len()` wide.
   */
  key_positions: Array<number>,
  bindings: number,
};

/**
 * One binding, as a panel draws it: the params driving it, the property it
 * drives, how it reads between cells, and the grid the author keyed.
 *
 * **The grid is `[y][x]`** — the transpose of the `cell: [x, y]` every
 * binding command takes, so `keys[cell[1]][cell[0]]` is the cell
 * [`Command::BindingKey`] would write. It is the full product of the params'
 * key positions, [`Self::width`] by [`Self::height`], with one row when
 * there is no `param_y`.
 *
 * **A `null` in `keys` is a cell nobody authored.** The model stores only the
 * cells a rigger set and derives the rest at puppet build, and "unset" is a
 * state they act on — it is not a zero. The exception is a `deform` binding,
 * which authors per-vertex offsets rather than one number: every one of its
 * cells reads `null` here and [`Self::authored`] is the only thing that says
 * which are set. For every other target `authored[y][x]` is exactly
 * `keys[y][x] != null`.
 */
export type BindingInfo = {
  /**
   * The property driven — plus `deform`, which only the deform commands
   * author.
   */
  target: BindingTarget,
  /**
   * The param along the grid's x axis.
   */
  param: ParamId,
  /**
   * The param along the grid's y axis. Absent when the grid is one row.
   */
  param_y?: ParamId | null,
  /**
   * How it reads between cells, as [`Command::BindingInterpolate`] takes
   * it back.
   */
  interpolate: Interpolate,
  /**
   * How many key positions `param` has, so how wide the grid is.
   */
  width: number,
  /**
   * How many key positions `param_y` has, or 1.
   */
  height: number,
  /**
   * The authored value at each cell, `[y][x]`, `null` where nothing was
   * authored.
   */
  keys: Array<Array<number | null>>,
  /**
   * Whether each cell was authored at all, `[y][x]`.
   */
  authored: Array<Array<boolean>>,
};

/**
 * One slot; `vertex` absent means unfilled, and the weld pairs naming it
 * skip it.
 */
export type SlotInfo = {
  id: SlotId,
  vertex: number | null,
};

/**
 * One weld: the two parts it joins, and the slot pairs between them.
 */
export type WeldInfo = {
  a: NodeId,
  b: NodeId,
  pairs: Array<SlotPair>,
};

/**
 * What a [`Command::Preview`] rendered. The pixels are the reply's payload;
 * this says how to read them.
 */
export type PreviewInfo = {
  width: number,
  height: number,
};

/**
 * A command that changes a session's model, or which sessions exist.
 *
 * The session's revision moves, so every view of it re-reads. These are the
 * commands that cost an undo entry and a React render, and the only ones
 * that must reach the editor that owns the model.
 */
export type EditCommandTag =
  | "session_new"
  | "session_open"
  | "session_close"
  | "save"
  | "node_add"
  | "node_set"
  | "node_reparent"
  | "node_reorder"
  | "node_move"
  | "node_duplicate"
  | "rename_id"
  | "mask_add"
  | "mask_set"
  | "mask_reorder"
  | "mask_delete"
  | "physics_set"
  | "physics_globals"
  | "node_delete"
  | "texture_add"
  | "param_add"
  | "param_set"
  | "param_delete"
  | "param_key_insert"
  | "param_key_delete"
  | "param_key_move"
  | "param_flip"
  | "binding_add"
  | "binding_key"
  | "binding_keys"
  | "binding_unset"
  | "binding_reset"
  | "binding_delete"
  | "binding_interpolate"
  | "binding_invert"
  | "binding_copy_key"
  | "deform_set"
  | "deform_vertices"
  | "mesh_set"
  | "mesh_auto"
  | "mesh_copy"
  | "slot_add"
  | "slot_fill"
  | "slot_clear"
  | "slot_delete"
  | "weld_weight"
  | "weld_set"
  | "weld_delete"
  | "physics_add"
  | "undo"
  | "redo"
  | "import_file"
  | "import_json"
  | "extension_set"
  | "extension_delete"
  | "import_manifest";
export type EditCommand = Extract<Command, { cmd: EditCommandTag }>;

/**
 * A command that publishes shared view state: pose, camera, selection.
 *
 * It goes to the editor because other clients read it back, and it changes no
 * model: no revision, no undo entry, invisible to a panel.
 */
export type PresenceCommandTag =
  | "presence_set";
export type PresenceCommand = Extract<Command, { cmd: PresenceCommandTag }>;

/**
 * A command that shows a live edit on a puppet without authoring it.
 *
 * The drag path. Whoever owns the puppet being drawn serves it — a client
 * with a local replica serves its own, and never asks the editor. A gesture
 * of any length repaints the canvas and re-renders nothing.
 */
export type ScratchCommandTag =
  | "scratch_deform";
export type ScratchCommand = Extract<Command, { cmd: ScratchCommandTag }>;

/**
 * A read that is a pure function of the model.
 *
 * A client holding a replica answers it locally, with no round trip. The
 * editor answers it the same way, from the same bytes.
 */
export type ReplicaQueryCommandTag =
  | "check"
  | "node_tree"
  | "node_info"
  | "texture_list"
  | "param_list"
  | "binding_list"
  | "slots"
  | "welds"
  | "unfilled_slots"
  | "extensions";
export type ReplicaQueryCommand = Extract<Command, { cmd: ReplicaQueryCommandTag }>;

/**
 * A read that needs the editor itself: its session bookkeeping, its store or
 * its renderer.
 *
 * A replica cannot answer one, so these always go over the wire.
 */
export type ServerQueryCommandTag =
  | "session_list"
  | "export_manifest"
  | "status"
  | "presence_get"
  | "preview"
  | "extension_get";
export type ServerQueryCommand = Extract<Command, { cmd: ServerQueryCommandTag }>;

/**
 * A command that reads, whoever answers it.
 *
 * The union of the two query kinds, for a caller that only cares that nothing
 * changed. A client routes on the halves; a caller sends either.
 */
export type QueryCommandTag = ReplicaQueryCommandTag | ServerQueryCommandTag;
export type QueryCommand = ReplicaQueryCommand | ServerQueryCommand;

/**
 * What bytes each command carries, keyed by its `cmd` tag.
 *
 * A command absent from this table carries none. `attachments` names what
 * travels in beside the command: a `fixed` name is one the command needs,
 * an `optional` one is a name whose own fields decide whether it is there,
 * and a `family` admits any number of `<name>:<suffix>` attachments.
 * `payload` says the reply carries bytes back.
 */
export const COMMAND_BYTES: Record<
  string,
  {
    attachments: ReadonlyArray<{
      kind: "fixed" | "optional" | "family";
      name: string;
    }>;
    payload: boolean;
  }
> = {
  texture_add: {
    attachments: [
      { kind: "fixed", name: "texture" },
    ],
    payload: false,
  },
  import_file: {
    attachments: [
      { kind: "fixed", name: "model" },
    ],
    payload: false,
  },
  import_json: {
    attachments: [
      { kind: "fixed", name: "structure" },
      { kind: "family", name: "texture" },
    ],
    payload: false,
  },
  import_manifest: {
    attachments: [
      { kind: "fixed", name: "manifest" },
      { kind: "family", name: "texture" },
    ],
    payload: false,
  },
  preview: {
    attachments: [],
    payload: true,
  },
  extension_set: {
    attachments: [
      { kind: "optional", name: "value" },
    ],
    payload: false,
  },
  extension_get: {
    attachments: [],
    payload: true,
  },
};
