// Generated by `cargo xtask ts` from crates/catchlight-editor-protocol.
// Do not edit: run `cargo xtask ts` and commit the result. CI fails on drift.

/**
 * One open editing session (one model and its undo history). Opaque: a
 * session is not part of any model, so it has no Id of its own.
 */
export type SessionId = number;

/**
 * The identity of a node. Unique within a model; generated as `<parent id>/<kind>-<8 hex>` by [`NodeId::generate`].
 */
export type NodeId = string;

/**
 * The identity of a param. Unique within a model; generated as `param-<8 hex>` by [`ParamId::generate`].
 */
export type ParamId = string;

/**
 * The identity of a texture. Unique within a model; generated as `tex-<8 hex>` by [`TexId::generate`].
 */
export type TexId = string;

/**
 * The identity of a seam, unique within the part that owns it — not within the model. Always authored.
 */
export type SeamId = string;

/**
 * The identity of a slot, unique within the seam that owns it — not within the part or the model. Always authored.
 */
export type SlotId = string;

export type Command =
  | {
    "cmd": "session_new",
    name: string | null,
  }
  | {
    "cmd": "session_open",
    path: string,
  }
  | {
    "cmd": "session_import",
    manifest_path: string,
  }
  | {
    "cmd": "manifest_requirements",
    manifest_path: string,
  }
  | {
    "cmd": "session_list"
  }
  | {
    "cmd": "session_close",
    session: SessionId,
  }
  | {
    "cmd": "save",
    session: SessionId,
    path: string | null,
  }
  | {
    "cmd": "export_manifest",
    session: SessionId,
    path: string,
  }
  | {
    "cmd": "status",
    session: SessionId,
  }
  | {
    "cmd": "check",
    session: SessionId,
  }
  | {
    "cmd": "node_tree",
    session: SessionId,
  }
  | {
    "cmd": "node_info",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "node_add",
    session: SessionId,
    parent: NodeId,
    kind: NodeKindArg,
    name: string | null,
  }
  | {
    "cmd": "node_set",
    session: SessionId,
    node: NodeId,
    /**
     * The label a person reads. Free to repeat; nothing is addressed by it.
     */
    name?: string | null,
    translate?: [number, number, number] | null,
    rotate?: [number, number, number] | null,
    scale?: [number, number] | null,
    z_order?: number | null,
    opacity?: number | null,
    enabled?: boolean | null,
    texture?: TexId | null,
    /**
     * Draw no texture at all. [`Self::texture`] says "point at this one" and
     * absent says "unchanged", so this is the only spelling for "none"; it
     * wins over `texture` the way
     * [`Command::PhysicsSet::clear_target_params`] wins over its
     * `target_params`. Ignored on a node that is not a part. Clearing the
     * last part drawing a texture takes the texture with it — see
     * [`ResponseBody::Node::dropped`].
     */
    clear_texture?: boolean,
    lock_to_root?: boolean | null,
    /**
     * Blend-mode name (Normal | Multiply | ColorDodge | …).
     */
    blend_mode?: string | null,
    tint?: [number, number, number] | null,
    screen_tint?: [number, number, number] | null,
    mask_threshold?: number | null,
    /**
     * Composite: forward mesh-group deformation to children.
     */
    propagate_meshgroup?: boolean | null,
    mg_dynamic?: boolean | null,
    mg_translate_children?: boolean | null,
  }
  | {
    "cmd": "node_reparent",
    session: SessionId,
    node: NodeId,
    to: NodeId,
  }
  | {
    "cmd": "node_reorder",
    session: SessionId,
    node: NodeId,
    index: number,
  }
  | {
    "cmd": "node_move",
    session: SessionId,
    node: NodeId,
    parent: NodeId,
    index: number,
  }
  | {
    "cmd": "node_duplicate",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "rename_id",
    session: SessionId,
    rename: Rename,
  }
  | {
    "cmd": "mask_add",
    session: SessionId,
    node: NodeId,
    source: NodeId,
    mode: string,
  }
  | {
    "cmd": "mask_set",
    session: SessionId,
    node: NodeId,
    index: number,
    mode: string,
  }
  | {
    "cmd": "mask_reorder",
    session: SessionId,
    node: NodeId,
    index: number,
    to: number,
  }
  | {
    "cmd": "mask_delete",
    session: SessionId,
    node: NodeId,
    index: number,
  }
  | {
    "cmd": "physics_set",
    session: SessionId,
    node: NodeId,
    /**
     * rigid | spring
     */
    kind: string | null,
    /**
     * xy | yx | angle_length | length_angle
     */
    map_mode: string | null,
    local_only: boolean | null,
    /**
     * The one or two params the driver writes (angle, length). Absent =
     * unchanged; see `clear_target_params` to detach.
     */
    target_params: Array<ParamId> | null,
    /**
     * Detach the driven params (wins over `target_params`).
     */
    clear_target_params: boolean,
    gravity: number | null,
    length: number | null,
    frequency: number | null,
    angle_damping: number | null,
    length_damping: number | null,
    output_scale: [number, number] | null,
  }
  | {
    "cmd": "physics_globals",
    session: SessionId,
    gravity: number | null,
    pixels_per_meter: number | null,
  }
  | {
    "cmd": "node_delete",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "texture_add",
    session: SessionId,
    node: NodeId,
    path: string,
  }
  | {
    "cmd": "texture_list",
    session: SessionId,
  }
  | {
    "cmd": "param_add",
    session: SessionId,
    name: string,
    min: number,
    max: number,
    default: number,
    key_positions: Array<number>,
  }
  | {
    "cmd": "param_list",
    session: SessionId,
  }
  | {
    "cmd": "param_set",
    session: SessionId,
    param: ParamId,
    name: string | null,
    min: number | null,
    max: number | null,
    default: number | null,
  }
  | {
    "cmd": "param_delete",
    session: SessionId,
    param: ParamId,
  }
  | {
    "cmd": "param_key_insert",
    session: SessionId,
    param: ParamId,
    value: number,
  }
  | {
    "cmd": "param_key_delete",
    session: SessionId,
    param: ParamId,
    index: number,
  }
  | {
    "cmd": "param_key_move",
    session: SessionId,
    param: ParamId,
    index: number,
    value: number,
  }
  | {
    "cmd": "param_flip",
    session: SessionId,
    param: ParamId,
  }
  | {
    "cmd": "binding_add",
    session: SessionId,
    node: NodeId,
    /**
     * tx|ty|sx|sy|rx|ry|rz|z_order|opacity|tint{r,g,b}|screentint{r,g,b}|outputscale{x,y}
     */
    target: string,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_key",
    session: SessionId,
    node: NodeId,
    target: string,
    /**
     * `[x, y]` index into the binding's key grid; `y` is 0 for a
     * one-param binding.
     */
    cell: [number, number],
    value: number,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_keys",
    session: SessionId,
    node: NodeId,
    cell: [number, number],
    entries: Array<BindingKeyEntry>,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_unset",
    session: SessionId,
    node: NodeId,
    target: string,
    cell: [number, number],
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_reset",
    session: SessionId,
    node: NodeId,
    target: string,
    cell: [number, number],
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_delete",
    session: SessionId,
    node: NodeId,
    target: string,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_interpolate",
    session: SessionId,
    node: NodeId,
    target: string,
    mode: string,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_invert",
    session: SessionId,
    node: NodeId,
    target: string,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_copy_key",
    session: SessionId,
    node: NodeId,
    target: string,
    from: [number, number],
    to: [number, number],
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "binding_list",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "deform_set",
    session: SessionId,
    node: NodeId,
    cell: [number, number],
    translate: [number, number] | null,
    rotate: number | null,
    scale: [number, number] | null,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "deform_vertices",
    session: SessionId,
    node: NodeId,
    cell: [number, number],
    offsets: Array<number>,
    param: ParamId,
    param_y?: ParamId | null,
  }
  | {
    "cmd": "mesh_set",
    session: SessionId,
    node: NodeId,
    verts: Array<number>,
    uvs: Array<number>,
    indices: Array<number>,
    origin: [number, number],
  }
  | {
    "cmd": "mesh_copy",
    session: SessionId,
    from: NodeId,
    to: NodeId,
  }
  | {
    "cmd": "seam_add",
    session: SessionId,
    node: NodeId,
    seam: SeamId,
  }
  | {
    "cmd": "seam_delete",
    session: SessionId,
    node: NodeId,
    seam: SeamId,
  }
  | {
    "cmd": "slot_add",
    session: SessionId,
    node: NodeId,
    seam: SeamId,
    slot: SlotId,
  }
  | {
    "cmd": "slot_fill",
    session: SessionId,
    node: NodeId,
    seam: SeamId,
    slot: SlotId,
    vertex: number,
  }
  | {
    "cmd": "slot_clear",
    session: SessionId,
    node: NodeId,
    seam: SeamId,
    slot: SlotId,
  }
  | {
    "cmd": "slot_delete",
    session: SessionId,
    node: NodeId,
    seam: SeamId,
    slot: SlotId,
  }
  | {
    "cmd": "seams",
    session: SessionId,
    node: NodeId,
  }
  | {
    "cmd": "welds",
    session: SessionId,
  }
  | {
    "cmd": "unfilled_slots",
    session: SessionId,
  }
  | {
    "cmd": "weld_set",
    session: SessionId,
    a: SeamAddr,
    b: SeamAddr,
    weights: Array<SlotWeight>,
  }
  | {
    "cmd": "physics_add",
    session: SessionId,
    parent: NodeId,
    name: string | null,
    kind: string,
    /**
     * The one or two params the driver writes (angle, length).
     */
    target_params: Array<ParamId>,
    length: number | null,
    gravity: number | null,
    frequency: number | null,
    angle_damping: number | null,
    length_damping: number | null,
  }
  | {
    "cmd": "undo",
    session: SessionId,
  }
  | {
    "cmd": "redo",
    session: SessionId,
  }
  | {
    "cmd": "presence_set",
    session: SessionId,
    pose: Array<ParamPose>,
    camera?: Camera | null,
    selection?: NodeId | null,
  }
  | {
    "cmd": "presence_get",
    session: SessionId,
  }
  | {
    "cmd": "scratch_deform",
    session: SessionId,
    node: NodeId,
    offsets: Array<number>,
  }
  | {
    "cmd": "preview",
    session: SessionId,
    pose: Array<ParamPose>,
    size: [number, number] | null,
    out: string | null,
  };

export type NodeKindArg =
  | "group"
  | "part"
  | "composite"
  | "mesh_group";

/**
 * Fields to change on a node; every field is optional (absent = unchanged).
 * Kind-specific fields are ignored on nodes of another kind: the colour fields
 * (`opacity`, `blend_mode`, `tint`, `screen_tint`) reach parts and composites
 * only, because a mesh group is never drawn and carries no colour.
 */
export type NodePatch = {
  /**
   * The label a person reads. Free to repeat; nothing is addressed by it.
   */
  name?: string | null,
  translate?: [number, number, number] | null,
  rotate?: [number, number, number] | null,
  scale?: [number, number] | null,
  z_order?: number | null,
  opacity?: number | null,
  enabled?: boolean | null,
  texture?: TexId | null,
  /**
   * Draw no texture at all. [`Self::texture`] says "point at this one" and
   * absent says "unchanged", so this is the only spelling for "none"; it
   * wins over `texture` the way
   * [`Command::PhysicsSet::clear_target_params`] wins over its
   * `target_params`. Ignored on a node that is not a part. Clearing the
   * last part drawing a texture takes the texture with it — see
   * [`ResponseBody::Node::dropped`].
   */
  clear_texture?: boolean,
  lock_to_root?: boolean | null,
  /**
   * Blend-mode name (Normal | Multiply | ColorDodge | …).
   */
  blend_mode?: string | null,
  tint?: [number, number, number] | null,
  screen_tint?: [number, number, number] | null,
  mask_threshold?: number | null,
  /**
   * Composite: forward mesh-group deformation to children.
   */
  propagate_meshgroup?: boolean | null,
  mg_dynamic?: boolean | null,
  mg_translate_children?: boolean | null,
};

/**
 * Which Id [`Command::RenameId`] changes, and to what.
 */
export type Rename =
  | {
    "kind": "node",
    from: NodeId,
    to: NodeId,
  }
  | {
    "kind": "param",
    from: ParamId,
    to: ParamId,
  }
  | {
    "kind": "texture",
    from: TexId,
    to: TexId,
  };

/**
 * The param, or the pair of params, a binding is keyed by. With `param_y`
 * the binding's grid spans both params' key positions and `cell` indexes
 * both; without it the grid is one row and `cell[1]` is 0.
 */
export type BindingParams = {
  param: ParamId,
  param_y?: ParamId | null,
};

export type BindingKeyEntry = {
  target: string,
  value: number,
};

/**
 * One param at one value — a pose is a list of these. Params are scalar, so
 * there is one number.
 */
export type ParamPose = {
  param: ParamId,
  value: number,
};

/**
 * One end of a weld: the seam, and the part carrying it.
 */
export type SeamAddr = {
  node: NodeId,
  seam: SeamId,
};

/**
 * One slot of a model, named in full.
 */
export type SlotAddr = {
  node: NodeId,
  seam: SeamId,
  slot: SlotId,
};

/**
 * One slot of a part's seam — the part is whatever carries the reply.
 */
export type SeamSlot = {
  seam: SeamId,
  slot: SlotId,
};

/**
 * A slot's share of the point its two welded vertices are pulled toward.
 */
export type SlotWeight = {
  slot: SlotId,
  weight: number,
};

/**
 * Ephemeral shared view state. Rides its own path — decoupled from the document
 * so scrubbing/panning generate zero document traffic and never persist.
 */
export type Presence = {
  pose: Array<ParamPose>,
  camera?: Camera | null,
  selection?: NodeId | null,
};

export type Camera = {
  center: [number, number],
  height: number,
};

/**
 * The server's answer. `Ok`/`Err` carry the request's `id`; `Event` is
 * unsolicited (a document changed on a session this client observes).
 */
export type Reply =
  | {
    "reply": "ok",
    id: number,
    /**
     * The addressed session's revision *after* this command, so a client
     * knows what its reply describes without a second round trip.
     *
     * Present whenever the command named a session — including one it
     * only read, and including the create/open/import commands, which
     * report the revision of the session they just made. Absent for the
     * editor-level commands that name no session at all, and for a
     * `session_close`, whose session is gone.
     */
    rev?: number | null,
    body: ResponseBody,
  }
  | {
    "reply": "err",
    id: number,
    code: ErrorCode,
    message: string,
  }
  | {
    "reply": "event"
  } & Event;

/**
 * Why a command was refused. A client that has to react — a commit gate
 * waiting on unfilled slots, a mesh editor offering to refill a seam —
 * branches on this rather than on the message text.
 */
export type ErrorCode =
  | "no_session"
  | "no_node"
  | "no_param"
  | "no_texture"
  | "bad_request"
  | "bad_target"
  | "nothing_to_undo"
  | "nothing_to_redo"
  | "no_save_path"
  | "unknown_seam"
  | "unknown_slot"
  | "duplicate_seam"
  | "duplicate_slot"
  | "weld_slot_mismatch"
  | "fragment"
  | "edit"
  | "manifest"
  | "io"
  | "image"
  | "preview"
  | "native_only";

export type ResponseBody =
  | {
    "result": "empty"
  }
  | {
    "result": "session",
    session: SessionId,
  }
  | {
    "result": "sessions",
    sessions: Array<SessionInfo>,
  }
  | {
    "result": "node",
    node: NodeId,
    /**
     * Textures the edit deleted, because no part draws them any more.
     * Every texture a model carries is drawn by a part, so repointing or
     * removing the last one takes the texture with it.
     */
    dropped?: Array<TexId>,
  }
  | {
    "result": "param",
    param: ParamId,
  }
  | {
    "result": "params",
    params: Array<ParamInfo>,
  }
  | {
    "result": "bindings",
    bindings: Array<BindingInfo>,
  }
  | {
    "result": "texture",
    texture: TexId,
    /**
     * Textures the edit deleted, because the part that had been drawing
     * them stopped and nothing else was. Every texture a model carries
     * is drawn by a part, so an upload that displaces the last user of
     * the old one takes it.
     */
    dropped?: Array<TexId>,
  }
  | {
    "result": "textures",
    textures: Array<TexInfo>,
  }
  | {
    "result": "tree",
    root: TreeNode,
  }
  | {
    "result": "node_info",
    node: NodeInfo,
  }
  | {
    "result": "status",
    status: StatusInfo,
  }
  | {
    "result": "warnings",
    warnings: Array<string>,
  }
  | {
    "result": "preview",
    preview: PreviewInfo,
  }
  | {
    "result": "saved",
    path: string,
  }
  | {
    "result": "presence",
    presence: Presence | null,
  }
  | {
    "result": "seams",
    seams: Array<SeamInfo>,
  }
  | {
    "result": "welds",
    welds: Array<WeldInfo>,
  }
  | {
    "result": "unfilled_slots",
    slots: Array<SlotAddr>,
  }
  | {
    "result": "emptied",
    node: NodeId,
    slots: Array<SeamSlot>,
  }
  | {
    "result": "manifest_requirements",
    textures: Array<string>,
  };

export type Event =
  | {
    "event": "document_changed",
    session: SessionId,
    rev: number,
  }
  | {
    "event": "sessions_changed"
  };

export type SessionInfo = {
  session: SessionId,
  title: string,
  file: string | null,
  dirty: boolean,
  rev: number,
  node_count: number,
};

export type StatusInfo = {
  title: string,
  node_count: number,
  param_count: number,
  texture_count: number,
  dirty: boolean,
  rev: number,
};

export type TreeNode = {
  /**
   * What the node is addressed by, here and in the file.
   */
  id: NodeId,
  /**
   * What a person reads. Free to repeat.
   */
  name: string,
  kind: string,
  z_order: number,
  enabled: boolean,
  children: Array<TreeNode>,
};

/**
 * One node in full: what [`NodePatch`] can set, plus the three things it
 * cannot — the node's Id, its kind and its parent.
 *
 * **The settable fields carry [`NodePatch`]'s own names.** An inspector reads
 * a value here, edits it, and sends it straight back in a
 * [`Command::NodeSet`] under the same key; a field that spelled itself
 * differently on the way out would be a rename nothing checks.
 *
 * A field a node's kind does not carry is absent, the way it is ignored on
 * the way in: the colour fields reach parts and composites only, `texture`
 * only a part, `mg_*` only a mesh group. `texture` is also absent on a part
 * that draws none, which `kind` tells apart from a node that could not have
 * one.
 */
export type NodeInfo = {
  /**
   * What the node is addressed by, here and in the file.
   */
  id: NodeId,
  /**
   * group | part | composite | mesh_group | physics — the same word
   * [`TreeNode::kind`] carries.
   */
  kind: string,
  /**
   * Absent on the root, which is the one node with no parent.
   */
  parent?: NodeId | null,
  /**
   * What a person reads. Free to repeat; nothing is addressed by it.
   */
  name: string,
  translate: [number, number, number],
  rotate: [number, number, number],
  scale: [number, number],
  z_order: number,
  enabled: boolean,
  lock_to_root: boolean,
  opacity?: number | null,
  /**
   * Blend-mode name (Normal | Multiply | ColorDodge | …).
   */
  blend_mode?: string | null,
  tint?: [number, number, number] | null,
  screen_tint?: [number, number, number] | null,
  mask_threshold?: number | null,
  /**
   * The part's albedo texture, absent when it draws none.
   */
  texture?: TexId | null,
  /**
   * Composite: forward mesh-group deformation to children.
   */
  propagate_meshgroup?: boolean | null,
  mg_dynamic?: boolean | null,
  mg_translate_children?: boolean | null,
};

export type TexInfo = {
  id: TexId,
  width: number,
  height: number,
};

export type ParamInfo = {
  /**
   * What the param is addressed by.
   */
  id: ParamId,
  /**
   * What a person reads. Free to repeat.
   */
  name: string,
  min: number,
  max: number,
  default: number,
  /**
   * Key positions, normalized 0..1 across `[min, max]`. Always at least
   * the two endpoints, so a binding's grid is `key_positions.len()` wide.
   */
  key_positions: Array<number>,
  bindings: number,
};

/**
 * One binding, as a panel draws it: the params driving it, the property it
 * drives, how it reads between cells, and the grid the author keyed.
 *
 * **The grid is `[y][x]`** — the transpose of the `cell: [x, y]` every
 * binding command takes, so `keys[cell[1]][cell[0]]` is the cell
 * [`Command::BindingKey`] would write. It is the full product of the params'
 * key positions, [`Self::width`] by [`Self::height`], with one row when
 * there is no `param_y`.
 *
 * **A `null` in `keys` is a cell nobody authored.** The model stores only the
 * cells a rigger set and derives the rest at puppet build, and "unset" is a
 * state they act on — it is not a zero. The exception is a `deform` binding,
 * which authors per-vertex offsets rather than one number: every one of its
 * cells reads `null` here and [`Self::authored`] is the only thing that says
 * which are set. For every other target `authored[y][x]` is exactly
 * `keys[y][x] != null`.
 */
export type BindingInfo = {
  /**
   * The property driven, spelled the way [`Command::BindingAdd`] and every
   * other binding command take it — plus `deform`, which only the deform
   * commands author.
   */
  target: string,
  /**
   * The param along the grid's x axis.
   */
  param: ParamId,
  /**
   * The param along the grid's y axis. Absent when the grid is one row.
   */
  param_y?: ParamId | null,
  /**
   * nearest | stepped | linear | cubic — the name
   * [`Command::BindingInterpolate`] takes back.
   */
  interpolate: string,
  /**
   * How many key positions `param` has, so how wide the grid is.
   */
  width: number,
  /**
   * How many key positions `param_y` has, or 1.
   */
  height: number,
  /**
   * The authored value at each cell, `[y][x]`, `null` where nothing was
   * authored.
   */
  keys: Array<Array<number | null>>,
  /**
   * Whether each cell was authored at all, `[y][x]`.
   */
  authored: Array<Array<boolean>>,
};

/**
 * A seam and what currently fills it.
 */
export type SeamInfo = {
  id: SeamId,
  slots: Array<SlotInfo>,
};

/**
 * One slot; `vertex` absent means unfilled, and welds skip it.
 */
export type SlotInfo = {
  id: SlotId,
  vertex: number | null,
};

export type WeldInfo = {
  a: SeamAddr,
  b: SeamAddr,
  weights: Array<SlotWeight>,
};

export type PreviewInfo = {
  path: string,
  width: number,
  height: number,
};

/**
 * A command that changes the document, or which documents exist.
 *
 * The session's revision moves, so every view of it re-reads. These are the
 * commands that cost an undo entry and a React render, and the only ones
 * that must reach the editor that owns the document.
 */
export type DocumentCommandTag =
  | "session_new"
  | "session_open"
  | "session_import"
  | "session_close"
  | "save"
  | "node_add"
  | "node_set"
  | "node_reparent"
  | "node_reorder"
  | "node_move"
  | "node_duplicate"
  | "rename_id"
  | "mask_add"
  | "mask_set"
  | "mask_reorder"
  | "mask_delete"
  | "physics_set"
  | "physics_globals"
  | "node_delete"
  | "texture_add"
  | "param_add"
  | "param_set"
  | "param_delete"
  | "param_key_insert"
  | "param_key_delete"
  | "param_key_move"
  | "param_flip"
  | "binding_add"
  | "binding_key"
  | "binding_keys"
  | "binding_unset"
  | "binding_reset"
  | "binding_delete"
  | "binding_interpolate"
  | "binding_invert"
  | "binding_copy_key"
  | "deform_set"
  | "deform_vertices"
  | "mesh_set"
  | "mesh_copy"
  | "seam_add"
  | "seam_delete"
  | "slot_add"
  | "slot_fill"
  | "slot_clear"
  | "slot_delete"
  | "weld_set"
  | "physics_add"
  | "undo"
  | "redo";
export type DocumentCommand = Extract<Command, { cmd: DocumentCommandTag }>;

/**
 * A command that publishes shared view state: pose, camera, selection.
 *
 * It goes to the editor because other clients read it back, and it changes no
 * document: no revision, no undo entry, invisible to a panel.
 */
export type PresenceCommandTag =
  | "presence_set";
export type PresenceCommand = Extract<Command, { cmd: PresenceCommandTag }>;

/**
 * A command that shows a live edit on a puppet without authoring it.
 *
 * The drag path. Whoever owns the puppet being drawn serves it — a client
 * with a local replica serves its own, and never asks the editor. A gesture
 * of any length repaints the canvas and re-renders nothing.
 */
export type ScratchCommandTag =
  | "scratch_deform";
export type ScratchCommand = Extract<Command, { cmd: ScratchCommandTag }>;

/**
 * A read that is a pure function of the model.
 *
 * A client holding a replica answers it locally, with no round trip. The
 * editor answers it the same way, from the same bytes.
 */
export type ReplicaQueryCommandTag =
  | "check"
  | "node_tree"
  | "node_info"
  | "texture_list"
  | "param_list"
  | "binding_list"
  | "seams"
  | "welds"
  | "unfilled_slots";
export type ReplicaQueryCommand = Extract<Command, { cmd: ReplicaQueryCommandTag }>;

/**
 * A read that needs the editor itself: its session bookkeeping, its store or
 * its renderer.
 *
 * A replica cannot answer one, so these always go over the wire.
 */
export type ServerQueryCommandTag =
  | "manifest_requirements"
  | "session_list"
  | "export_manifest"
  | "status"
  | "presence_get"
  | "preview";
export type ServerQueryCommand = Extract<Command, { cmd: ServerQueryCommandTag }>;

/**
 * A command that reads, whoever answers it.
 *
 * The union of the two query kinds, for a caller that only cares that nothing
 * changed. A client routes on the halves; a caller sends either.
 */
export type QueryCommandTag = ReplicaQueryCommandTag | ServerQueryCommandTag;
export type QueryCommand = ReplicaQueryCommand | ServerQueryCommand;
