/**
 * The wasm module's JS surface, declared structurally rather than imported.
 *
 * `@catchlight/wasm` is generated by `cargo xtask wasm` and is never a
 * dependency of this package: everything here has to typecheck and test
 * without 2 MiB of WebAssembly, and each class below is small enough that a
 * fake is a few lines. A host passes the real module in.
 *
 * The split these types encode is the whole architecture. The **editor** owns
 * the document and is the only thing that answers a command. The **replica**
 * is this tab's copy of one session — model, puppet and render cache — and it
 * is never mutated locally: it moves only when a backend feeds it a document
 * state at a revision, forward only. The **viewport** draws a replica on a
 * canvas and owns its own frame loop. The **gpu** is one device, acquired from
 * the first canvas an editor draws on and shared by everything under it.
 *
 * Two things cross the boundary as JSON strings — a command and a query — and
 * everything per-frame or per-pointer-move is a typed method instead, because
 * a drag must not spend a `JSON.parse` per event.
 */

import type { NodeId, ParamId, TexId } from "./protocol.gen.js";

/**
 * What wasm-bindgen puts on every class it exports.
 *
 * Both members are required rather than optional, and that is not a style
 * choice: [`WasmModule`]'s `Viewport` is a construct signature taking a `Gpu`
 * and a `Replica`, and a construct signature's parameters are checked
 * contravariantly — so the generated module is assignable to [`WasmModule`]
 * only if the types here are assignable to the generated classes, and an
 * optional member is not assignable to a required one. Writing them down is
 * what lets a host pass the module in without an assertion.
 *
 * Nothing in this package calls either one on a value it did not create; a
 * fake implements both in a line.
 */
export interface WasmOwned {
  free(): void;
  /** What `using` calls. */
  [Symbol.dispose](): void;
}

/** The in-tab editor: an `Editor` from `catchlight-editor-server`. */
export interface WasmEditor extends WasmOwned {
  /** One JSON `Request` in, one JSON `Reply` out — the wire protocol verbatim. */
  handle(requestJson: string): string;
  /**
   * The JSON `Event`s emitted since the last drain, in order. A pull, not a
   * callback: Rust never calls back into JS, so a backend drains after every
   * `handle` and dispatches what it got.
   */
  drainEvents(): string[];
  /** Byte staging: what a `path` key resolves to inside the editor. */
  putBytes(key: string, bytes: Uint8Array): void;
  takeBytes(key: string): Uint8Array | undefined;
  stagedKeys(): string[];
}

/**
 * One WebGPU (or WebGL2) device, shared by everything below one editor.
 *
 * It is acquired from a canvas, and on WebGL2 that canvas is the only surface
 * it can ever present into: an adapter there is enumerated from a context and
 * draws into the context it came from. WebGPU has no such tie, so a second
 * canvas works on it and does not on the fallback.
 */
export interface WasmGpu extends WasmOwned {
  /**
   * `max_texture_dimension_2d`: the largest backing store a canvas may have on
   * either axis. Configuring a surface past it fails and the viewport goes
   * black with no other symptom, which is why the sizing clamps to it.
   */
  maxSize(): number;
  /** `"webgpu"` or `"webgl2"`. */
  backend(): string;
}

/**
 * What a structure names that the replica does not hold yet, with the hints a
 * fetched payload is decoded by.
 *
 * Only `id` is read here — the encoding and alpha hints exist for whoever
 * fetches the bytes, and this package passes them to nobody.
 */
export interface TextureRequest {
  id: TexId;
  encoding: string;
  alpha: string;
}

/** One session's model, puppet and render cache, in this tab. */
export interface WasmReplica extends WasmOwned {
  /** The document revision this replica currently holds. */
  rev(): number;

  /** The `TextureRequest[]` a structure names and this replica lacks, as JSON. */
  texturesNeeded(structure: Uint8Array): string;
  /** Holds a texture payload under its id, for the structures that name it. */
  putTexture(id: TexId, bytes: Uint8Array): void;
  /**
   * Applies a structure-only container at `rev`. Forward only: a `rev` at or
   * below the current one is ignored and returns false. Throws a string when
   * the structure is malformed or names a texture that was not put, leaving
   * the model untouched.
   */
  applyStructure(structure: Uint8Array, rev: number): boolean;
  /** In-tab handoff: replace from the editor's own model. Returns the rev. */
  syncFromEditor(editor: WasmEditor, session: number): number;

  /** A `ReplicaQuery` as a JSON `Request`, answered as a JSON `Reply`. */
  query(requestJson: string): string;

  setParam(id: ParamId, value: number): boolean;
  paramValue(id: ParamId): number | undefined;
  /** Per-vertex offsets as pairs `[dx0, dy0, dx1, dy1, ...]`. */
  scratchDeform(node: NodeId, offsets: Float32Array): boolean;
  clearScratchDeform(node: NodeId): boolean;
  /** Absolute values; `NaN` leaves what the fold produced for that field. */
  scratchTransform(
    node: NodeId,
    tx: number,
    ty: number,
    tz: number,
    rx: number,
    ry: number,
    rz: number,
    sx: number,
    sy: number,
    zOrder: number,
    opacity: number,
  ): boolean;
  clearScratchTransform(node: NodeId): boolean;
  clearAllScratch(): void;

  /**
   * The node's evaluated world transform after the last tick: 16 floats,
   * column-major. `undefined` when the model holds no such node.
   */
  nodeWorldTransform(node: NodeId): Float32Array | undefined;
  /**
   * The node's authored local translation `[x, y, z]` moved by a world-space
   * delta, expressed in its parent's frame — what a drag previews and then
   * commits. `undefined` when the model holds no such node.
   */
  translationAfterWorldDelta(node: NodeId, dx: number, dy: number): Float32Array | undefined;
  /**
   * The world-space box the last tick left the drawn geometry in:
   * `[min_x, min_y, max_x, max_y]` in world units, Y-up. `undefined` when the
   * model draws nothing — an empty document, or one whose every part is
   * disabled, untextured or fully transparent. What a "frame the model" camera
   * is computed from, and posed rather than at rest, so a limb physics has
   * swung out is inside the box.
   */
  bounds(): Float32Array | undefined;
}

/**
 * The renderer's surface. It owns the frame loop; this side owns the element,
 * because only the page knows how big it is.
 */
export interface WasmViewport extends WasmOwned {
  /** Marks the picture stale; at most one frame follows. */
  invalidate(): void;
  /** Backing store in device pixels; the caller has set the canvas to match. */
  resize(width: number, height: number): void;
  setCamera(centerX: number, centerY: number, height: number): void;
  /** Starts the rAF loop; idempotent. */
  start(): void;
  /** Cancels it; idempotent, and `start` works again afterwards. */
  stop(): void;
}

/**
 * The named exports of `@catchlight/wasm`, as this package uses them.
 *
 * `Gpu.acquire` is the one asynchronous call in the module — an adapter and a
 * device are promises. It takes a canvas because WebGL2 has no other way in:
 * there the adapter is enumerated from a context, so no device can exist
 * before the first canvas does. WebGPU ignores the canvas and is tried first.
 * A `Replica` therefore holds no device at all; the viewport built on it
 * brings one. Everything after that call is synchronous, which is what lets a
 * query answer inside a React render and a drag run without an `await`.
 */
export interface WasmModule {
  CatchlightEditor: new () => WasmEditor;
  Gpu: { acquire(canvas: HTMLCanvasElement): Promise<WasmGpu> };
  Replica: new () => WasmReplica;
  Viewport: new (gpu: WasmGpu, replica: WasmReplica, canvas: HTMLCanvasElement) => WasmViewport;
}
