# Generated by `cargo xtask generate python` from crates/catchlight-editor-protocol.
# Do not edit: run `cargo xtask generate` and commit the result. CI fails on drift.

"""The catchlight editor protocol, as Python.

A client builds a command, calls `to_wire()` on it, and sends the result next
to a correlation `id` of its own. The editor answers with a line `parse_reply`
turns back into a `Reply`, or with an unsolicited `Event`.

Ids are plain strings — the same ones the model file stores — and a `SessionId`
is an int the editor allocates. Every command carries `CMD`, the tag it travels
under, and `KIND`, what applying it does to the document; a client routes by the
second. Nothing here is a transport: this module opens no socket and holds no
state.

Most optional fields are two-state: a value, or `None` for "leave the key off".
A few are three-state, annotated `T | Clear | None` — those spell "set this to
nothing" with the `CLEAR` singleton, which `to_wire()` writes as JSON null.
`NodePatch.texture` is one: `None` leaves the part drawing what it drew, `CLEAR`
makes it draw none, and a `TexId` points it at that texture.
"""

from __future__ import annotations

import dataclasses
from collections.abc import Mapping
from dataclasses import dataclass, field
from enum import StrEnum
from functools import lru_cache
from types import UnionType
from typing import Any, ClassVar, Union, get_args, get_origin, get_type_hints


class CommandKind(StrEnum):
    """What applying a command does to the document it addresses.

    This is what a client routes by: one send method per kind, so picking
    the wrong one is a type error rather than a missing repaint.
    """

    # A command that changes the document, or which documents exist.
    #
    # The session's revision moves, so every view of it re-reads. These are the
    # commands that cost an undo entry and a React render, and the only ones
    # that must reach the editor that owns the document.
    DOCUMENT = "document"

    # A command that publishes shared view state: pose, camera, selection.
    #
    # It goes to the editor because other clients read it back, and it changes no
    # document: no revision, no undo entry, invisible to a panel.
    PRESENCE = "presence"

    # A command that shows a live edit on a puppet without authoring it.
    #
    # The drag path. Whoever owns the puppet being drawn serves it — a client
    # with a local replica serves its own, and never asks the editor. A gesture
    # of any length repaints the canvas and re-renders nothing.
    SCRATCH = "scratch"

    # A read that is a pure function of the model.
    #
    # A client holding a replica answers it locally, with no round trip. The
    # editor answers it the same way, from the same bytes.
    REPLICA_QUERY = "replica_query"

    # A read that needs the editor itself: its session bookkeeping, its store or
    # its renderer.
    #
    # A replica cannot answer one, so these always go over the wire.
    SERVER_QUERY = "server_query"


class Clear:
    """The one value that means "set this field to nothing".

    `None` on a field means the key is left off entirely, so a field that has
    to be able to say "nothing" as well as "unchanged" needs a third word for
    it. Fields annotated `T | Clear | None` take `CLEAR`, and `to_wire()`
    writes it as JSON null.
    """

    __slots__ = ()

    def __repr__(self) -> str:
        return "CLEAR"


CLEAR = Clear()


def _wire(value: Any) -> Any:
    """One value, as JSON carries it."""
    if isinstance(value, Clear):
        return None
    if dataclasses.is_dataclass(value) and not isinstance(value, type):
        return _wire_fields(value)
    if isinstance(value, StrEnum):
        return value.value
    if isinstance(value, (list, tuple)):
        return [_wire(item) for item in value]
    return value


def _wire_fields(obj: Any) -> dict[str, Any]:
    """One dataclass, as JSON carries it: its tag, then every field it set.

    A field left `None` is left off entirely rather than sent as null. Almost
    every optional field on this wire has a serde default, so absent and null
    mean the same thing to the editor, and absent is the shorter of the two.
    A three-state field is the exception, and says its null with `CLEAR`.
    """
    cls = type(obj)
    out: dict[str, Any] = {}
    tag_field = getattr(cls, "TAG_FIELD", None)
    if tag_field is not None:
        out[tag_field] = cls.TAG
    names: Mapping[str, str] = getattr(cls, "WIRE", {})
    flat: tuple[str, ...] = getattr(cls, "FLATTEN", ())
    for spec in dataclasses.fields(obj):
        value = getattr(obj, spec.name)
        if value is None:
            continue
        if spec.name in flat:
            out.update(_wire(value))
            continue
        out[names.get(spec.name, spec.name)] = _wire(value)
    return out


@lru_cache(maxsize=None)
def _hints(cls: type) -> dict[str, Any]:
    return get_type_hints(cls)


def _decode(annotation: Any, value: Any) -> Any:
    """One value, as the annotation says to read it."""
    origin = get_origin(annotation)
    if origin is UnionType or origin is Union:
        if value is None:
            # Only a three-state field has a null to tell from an absent key.
            return CLEAR if Clear in get_args(annotation) else None
        arms = [
            arm
            for arm in get_args(annotation)
            if arm is not type(None) and arm is not Clear
        ]
        if len(arms) == 1:
            return _decode(arms[0], value)
        for arm in arms:
            tag_field = getattr(arm, "TAG_FIELD", None)
            if (
                tag_field is not None
                and isinstance(value, Mapping)
                and value.get(tag_field) == arm.TAG
            ):
                return _decode_class(arm, value)
        raise ValueError(f"no variant of {annotation} matches {value!r}")
    if origin is list:
        (arm,) = get_args(annotation)
        return [_decode(arm, item) for item in value]
    if origin is tuple:
        arms = get_args(annotation)
        return tuple(_decode(arm, item) for arm, item in zip(arms, value, strict=True))
    if isinstance(annotation, type):
        if issubclass(annotation, StrEnum):
            return annotation(value)
        if dataclasses.is_dataclass(annotation):
            return _decode_class(annotation, value)
    return value


def _decode_class(cls: Any, data: Mapping[str, Any]) -> Any:
    """One JSON object as an instance of `cls`.

    A key that is absent or null falls back to the field's default — except on
    a three-state field, where a null present in `data` is `CLEAR` rather than
    the default. A field with no default is an error naming the key, because a
    reply that lost one is not a reply this client can act on. A field named in
    `FLATTEN` is read from `data` itself, which is where an internally tagged
    newtype variant puts it.
    """
    hints = _hints(cls)
    names: Mapping[str, str] = getattr(cls, "WIRE", {})
    flat: tuple[str, ...] = getattr(cls, "FLATTEN", ())
    kwargs: dict[str, Any] = {}
    for spec in dataclasses.fields(cls):
        if spec.name in flat:
            kwargs[spec.name] = _decode(hints[spec.name], data)
            continue
        key = names.get(spec.name, spec.name)
        present = data.get(key)
        if present is not None:
            kwargs[spec.name] = _decode(hints[spec.name], present)
        elif key in data and Clear in get_args(hints[spec.name]):
            kwargs[spec.name] = CLEAR
        elif (
            spec.default is dataclasses.MISSING
            and spec.default_factory is dataclasses.MISSING
        ):
            raise ValueError(f"{cls.__name__} needs {key!r}")
    return cls(**kwargs)


# One open editing session (one model and its undo history). Opaque: a
# session is not part of any model, so it has no Id of its own.
SessionId = int

# The identity of a node. Unique within a model; generated as `<parent id>/<kind>-<8 hex>` by [`NodeId::generate`].
NodeId = str

# The identity of a param. Unique within a model; generated as `param-<8 hex>` by [`ParamId::generate`].
ParamId = str

# The identity of a texture. Unique within a model; generated as `tex-<8 hex>` by [`TexId::generate`].
TexId = str

# The identity of a seam, unique within the part that owns it — not within the model. Generated as `seam-<8 hex>` by [`SeamId::generate`].
SeamId = str

# The identity of a slot, unique within the seam that owns it — not within the part or the model. Generated as `slot-<8 hex>` by [`SlotId::generate`].
SlotId = str


@dataclass(frozen=True, kw_only=True)
class SessionNew:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "session_new"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    name: str | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SessionOpen:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "session_open"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    path: str

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SessionImport:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "session_import"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    manifest_path: str

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ManifestRequirements:
    """The storage keys [`Command::SessionImport`] would read for this
    manifest, resolved relative to the manifest's own key.

    A client whose store is not the editor's — a browser staging bytes it
    fetched — asks this first and stages exactly these keys, so the import
    itself never has to go looking for a file that is not there yet.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "manifest_requirements"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.SERVER_QUERY

    manifest_path: str

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SessionList:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "session_list"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.SERVER_QUERY

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SessionClose:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "session_close"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class Save:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "save"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    path: str | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ExportManifest:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "export_manifest"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.SERVER_QUERY

    session: SessionId
    path: str

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class Status:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "status"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.SERVER_QUERY

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class Check:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "check"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class NodeTree:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_tree"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class CommandNodeInfo:
    """Everything an inspector shows for one node: what [`NodePatch`] can set,
    under the same field names, plus the node's kind, its parent, its Id
    and the size of the mesh it holds. What [`Command::NodeTree`] carries
    is what a tree row draws; this is the rest.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_info"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId
    node: NodeId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class NodeAdd:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_add"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    parent: NodeId
    kind: NodeKindArg
    name: str | None = None
    # The Id to create it under. Absent generates one; an Id the model
    # already carries is [`ErrorCode::DuplicateId`].
    node: NodeId | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class NodeSet:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_set"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    # The label a person reads. Free to repeat; nothing is addressed by it.
    name: str | None = None
    translate: tuple[float, float, float] | None = None
    rotate: tuple[float, float, float] | None = None
    scale: tuple[float, float] | None = None
    z_order: float | None = None
    opacity: float | None = None
    enabled: bool | None = None
    # The texture the part draws, in three states: absent leaves it as it
    # is, `null` draws none, an Id draws that one. Ignored on a node that is
    # not a part. Dropping the last part drawing a texture takes the texture
    # with it — see [`ResponseBody::Node::dropped`].
    texture: TexId | Clear | None = None
    lock_to_root: bool | None = None
    blend_mode: BlendMode | None = None
    tint: tuple[float, float, float] | None = None
    screen_tint: tuple[float, float, float] | None = None
    mask_threshold: float | None = None
    # Composite: forward mesh-group deformation to children.
    propagate_meshgroup: bool | None = None
    mg_dynamic: bool | None = None
    mg_translate_children: bool | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class NodeReparent:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_reparent"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    to: NodeId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class NodeReorder:
    """Move a node within its parent's children (clamped to the end)."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_reorder"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    index: int

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class NodeMove:
    """Reparent + position in one undoable step: `node` becomes `parent`'s
    child at `index` (clamped).
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_move"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    parent: NodeId
    index: int

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class NodeDuplicate:
    """Deep-copy a node's subtree as its next sibling (bindings and
    subtree-internal mask references come along). The copies get fresh
    generated Ids.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_duplicate"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class RenameId:
    """Change a node's, a param's or a texture's Id, rewriting every
    reference this model holds to it.

    **Breaking for addons.** An addon reaches into a base model by Id, so
    renaming one is exactly as breaking as deleting it: nothing outside
    this model is rewritten and there is no alias left behind.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "rename_id"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    rename: Rename

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class MaskAdd:
    """Append a mask source to a Part/Composite."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "mask_add"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    source: NodeId
    mode: MaskMode

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class MaskSet:
    """Change the mode of the mask at `index`."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "mask_set"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    index: int
    mode: MaskMode

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class MaskReorder:
    """Move the mask at `index` to position `to` (clamped)."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "mask_reorder"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    index: int
    to: int

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class MaskDelete:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "mask_delete"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    index: int

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class PhysicsSet:
    """Change fields on a SimplePhysics node; absent = unchanged."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "physics_set"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    kind: PhysicsKind | None = None
    map_mode: PhysicsMapMode | None = None
    local_only: bool | None = None
    # The params the driver writes ([`PhysicsTargets`]). Absent leaves
    # both outputs as they are; present, both become exactly what it
    # says, so `{}` detaches both and `{"length": "len"}` binds the
    # second output and unbinds the first.
    target_params: PhysicsTargets | None = None
    gravity: float | None = None
    length: float | None = None
    frequency: float | None = None
    angle_damping: float | None = None
    length_damping: float | None = None
    output_scale: tuple[float, float] | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class PhysicsGlobals:
    """Model-level physics constants."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "physics_globals"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    gravity: float | None = None
    pixels_per_meter: float | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class NodeDelete:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "node_delete"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class TextureAdd:
    """Read an image from `path` and give it to `node`, which has to be a
    part: a texture is added and assigned in one edit. If that part was
    the last thing drawing whatever it drew before, that texture goes with
    this edit — see [`ResponseBody::Texture`].
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "texture_add"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    path: str
    # The Id to create it under. Absent generates one; an Id the model
    # already carries is [`ErrorCode::DuplicateId`].
    texture: TexId | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class TextureList:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "texture_list"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ParamAdd:
    """Create a scalar param. `key_positions` are normalized 0..1 (empty =
    the two endpoints).
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "param_add"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    name: str
    min: float = 0.0
    max: float = 1.0
    default: float = 0.0
    key_positions: list[float] = field(default_factory=list)
    # The Id to create it under. Absent generates one; an Id the model
    # already carries is [`ErrorCode::DuplicateId`].
    param: ParamId | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ParamList:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "param_list"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ParamSet:
    """Change param metadata; absent = unchanged. Key positions are
    normalized, so a range change doesn't move them.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "param_set"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    name: str | None = None
    min: float | None = None
    max: float | None = None
    default: float | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ParamDelete:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "param_delete"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ParamKeyInsert:
    """Insert a key position at normalized `value`, strictly inside (0, 1).
    Authored cells shift; the new row/column derives.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "param_key_insert"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    value: float

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ParamKeyDelete:
    """Remove an interior key position; its authored cells are dropped."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "param_key_delete"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    index: int

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ParamKeyMove:
    """Move an interior key position to normalized `value` (must stay
    strictly between its neighbors).
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "param_key_move"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    index: int
    value: float

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ParamFlip:
    """Mirror the param (key positions reflect, cells move to the mirrored
    index; values untouched — compose with BindingInvert).
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "param_flip"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingAdd:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_add"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    target: ScalarTarget

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingKey:
    """Author one scalar keypoint (auto-creates the binding)."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_key"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    target: ScalarTarget
    # `[x, y]` index into the binding's key grid; `y` is 0 for a
    # one-param binding.
    cell: tuple[int, int]
    value: float

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingKeys:
    """Author several scalar keypoints at one cell in one undoable step (a
    gizmo drag commits tx+ty together).
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_keys"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    cell: tuple[int, int]
    entries: list[BindingKeyEntry]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingUnset:
    """Un-author a keypoint (back to derived)."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_unset"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    target: BindingTarget
    cell: tuple[int, int]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingReset:
    """Author the identity value at a keypoint."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_reset"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    target: BindingTarget
    cell: tuple[int, int]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingDelete:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_delete"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    target: BindingTarget

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingInterpolate:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_interpolate"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    target: BindingTarget
    mode: Interpolate

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingInvert:
    """Negate every authored value."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_invert"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    target: BindingTarget

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingCopyKey:
    """Author the value evaluated at `from` into cell `to`."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_copy_key"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT
    WIRE: ClassVar[Mapping[str, str]] = {
        "from_": "from",
    }

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    target: BindingTarget
    from_: tuple[int, int]
    to: tuple[int, int]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class BindingList:
    """Every binding on one node: what drives it, how it reads between its
    cells, and the grid the author keyed.

    [`ParamInfo::bindings`] counts what a param drives and names none of
    it, so this is the read a binding panel is drawn from.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "binding_list"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId
    node: NodeId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class DeformSet:
    """Author a deform keypoint from an affine applied to the part's rest mesh."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "deform_set"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    cell: tuple[int, int]
    translate: tuple[float, float] | None = None
    rotate: float | None = None
    scale: tuple[float, float] | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class DeformVertices:
    """Author per-vertex deform offsets, one `[dx, dy]` per mesh vertex and in
    the mesh's own order. This is what commits a live drag.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "deform_vertices"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    param: ParamId
    param_y: ParamId | None = None
    node: NodeId
    cell: tuple[int, int]
    offsets: list[tuple[float, float]]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class MeshSet:
    """Replace a Part/MeshGroup mesh; every deform binding on the node is
    re-fitted onto the new topology in the same undoable step. Answers
    with the seam slots the new mesh emptied.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "mesh_set"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    # One `[x, y]` per vertex.
    verts: list[tuple[float, float]]
    # One `[u, v]` per vertex, as many as `verts`.
    uvs: list[tuple[float, float]]
    # One `[a, b, c]` per triangle, each a `verts` index.
    indices: list[tuple[int, int, int]]
    origin: tuple[float, float]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class MeshAuto:
    """Derive a part's mesh from its own texture's alpha and apply it, with
    the same deform re-fit and the same emptied-slot reply as
    [`Command::MeshSet`].

    The editor does the tracing: it holds the texture bytes, and a client
    that traced them itself would have to decode an image, agree on the
    UV mapping, and send back a mesh — three chances to disagree with the
    editor about what the part looks like.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "mesh_auto"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    # Absent is [`AutoMesh::Contour`] with every knob at its default.
    mode: AutoMesh | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class MeshCopy:
    """Copy `from`'s mesh onto `to` (with the same deform re-fit and the same
    emptied-slot reply).
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "mesh_copy"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT
    WIRE: ClassVar[Mapping[str, str]] = {
        "from_": "from",
    }

    session: SessionId
    from_: NodeId
    to: NodeId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SeamAdd:
    """Add a seam to a part."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "seam_add"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    # Absent generates one (`seam-<8 hex>`, re-drawn until it is free on
    # the part). The reply names it either way.
    seam: SeamId | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SeamDelete:
    """Remove a seam, and every weld that named it."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "seam_delete"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    seam: SeamId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SlotAdd:
    """Add a slot to a seam. The slot lands unfilled, and reaches every seam
    welded to this one at [`catchlight_core::DEFAULT_SLOT_WEIGHT`] — a
    weld pairs two seams slot by slot, so their slot sets are one set.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "slot_add"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    seam: SeamId
    # Absent generates one (`slot-<8 hex>`), free on every seam welded to
    # this one. The reply names it either way.
    slot: SlotId | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SlotFill:
    """Point a slot at one of the part's vertices."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "slot_fill"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    seam: SeamId
    slot: SlotId
    vertex: int

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SlotClear:
    """Unfill a slot. Welds keep it and skip it until it is filled again."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "slot_clear"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    seam: SeamId
    slot: SlotId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class SlotDelete:
    """Remove a slot — from this seam and from every seam welded to it."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "slot_delete"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    node: NodeId
    seam: SeamId
    slot: SlotId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class Seams:
    """The seams a part carries, with what fills each slot."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "seams"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId
    node: NodeId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class Welds:
    """Every weld in the model."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "welds"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class UnfilledSlots:
    """Every slot in the model no vertex fills. A re-meshed part empties its
    slots, so this is what a commit gate reads.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "unfilled_slots"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.REPLICA_QUERY

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class WeldWeight:
    """Move one slot's share of one weld's meeting point, leaving every other
    weight where it is — what a slider sends. [`Command::WeldSet`] can only
    rewrite a weld whole, so moving one weight through it means reading the
    rest back and sending them again unchanged.

    `weight` is the share of the end named `a`, whichever way round the
    weld happens to be stored, and it has to be within `0..=1` — a share
    outside that has no meaning to flip.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "weld_weight"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    a: SeamAddr
    b: SeamAddr
    slot: SlotId
    weight: float

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class WeldSet:
    """Weld two seams together, replacing any weld already pairing them.
    Empty `weights` welds every slot at
    [`catchlight_core::DEFAULT_SLOT_WEIGHT`].
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "weld_set"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    a: SeamAddr
    b: SeamAddr
    weights: list[SlotWeight] = field(default_factory=list)

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class WeldDelete:
    """Unmake the weld pairing two seams, named in either order. Both seams
    and every slot on them stay; only the pairing goes — which is what
    tells this apart from [`Command::SeamDelete`], the only other way a
    weld comes undone. [`ErrorCode::UnknownWeld`] if nothing pairs them.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "weld_delete"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    a: SeamAddr
    b: SeamAddr

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class PhysicsAdd:
    """Add a SimplePhysics node."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "physics_add"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId
    parent: NodeId
    name: str | None = None
    kind: PhysicsKind
    # The params the driver writes ([`PhysicsTargets`]). Absent binds
    # neither output.
    target_params: PhysicsTargets | None = None
    length: float | None = None
    gravity: float | None = None
    frequency: float | None = None
    angle_damping: float | None = None
    length_damping: float | None = None
    # The Id to create it under. Absent generates one; an Id the model
    # already carries is [`ErrorCode::DuplicateId`].
    node: NodeId | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class Undo:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "undo"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class Redo:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "redo"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.DOCUMENT

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class PresenceSet:
    """Publish ephemeral view state (pose / camera / selection) — a separate
    path from the document: never bumps rev, never undone, never saved.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "presence_set"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.PRESENCE

    session: SessionId
    pose: list[ParamPose] = field(default_factory=list)
    camera: Camera | None = None
    selection: NodeId | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class PresenceGet:
    """Read the session's current shared presence (latest publisher wins)."""

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "presence_get"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.SERVER_QUERY

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ScratchDeform:
    """Show a deform on the session's puppet without authoring it: the live
    half of a vertex drag. A [`CommandKind::Scratch`], so a drag of any
    length produces no revision and no undo entry; committing it is
    [`Command::DeformVertices`], which produces exactly one.

    `offsets` is one `[dx, dy]` per mesh vertex, in the mesh's own order;
    an empty list clears the scratch deform. It is dropped the next time
    the model changes, because the puppet rebakes.
    """

    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "scratch_deform"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.SCRATCH

    session: SessionId
    node: NodeId
    offsets: list[tuple[float, float]]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class Preview:
    TAG_FIELD: ClassVar[str] = "cmd"
    TAG: ClassVar[str] = "preview"
    CMD: ClassVar[str] = TAG
    KIND: ClassVar[CommandKind] = CommandKind.SERVER_QUERY

    session: SessionId
    pose: list[ParamPose] = field(default_factory=list)
    size: tuple[int, int] | None = None
    out: str | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


Command = (
    SessionNew
    | SessionOpen
    | SessionImport
    | ManifestRequirements
    | SessionList
    | SessionClose
    | Save
    | ExportManifest
    | Status
    | Check
    | NodeTree
    | CommandNodeInfo
    | NodeAdd
    | NodeSet
    | NodeReparent
    | NodeReorder
    | NodeMove
    | NodeDuplicate
    | RenameId
    | MaskAdd
    | MaskSet
    | MaskReorder
    | MaskDelete
    | PhysicsSet
    | PhysicsGlobals
    | NodeDelete
    | TextureAdd
    | TextureList
    | ParamAdd
    | ParamList
    | ParamSet
    | ParamDelete
    | ParamKeyInsert
    | ParamKeyDelete
    | ParamKeyMove
    | ParamFlip
    | BindingAdd
    | BindingKey
    | BindingKeys
    | BindingUnset
    | BindingReset
    | BindingDelete
    | BindingInterpolate
    | BindingInvert
    | BindingCopyKey
    | BindingList
    | DeformSet
    | DeformVertices
    | MeshSet
    | MeshAuto
    | MeshCopy
    | SeamAdd
    | SeamDelete
    | SlotAdd
    | SlotFill
    | SlotClear
    | SlotDelete
    | Seams
    | Welds
    | UnfilledSlots
    | WeldWeight
    | WeldSet
    | WeldDelete
    | PhysicsAdd
    | Undo
    | Redo
    | PresenceSet
    | PresenceGet
    | ScratchDeform
    | Preview
)

COMMAND_VARIANTS: dict[str, type[Command]] = {
    "session_new": SessionNew,
    "session_open": SessionOpen,
    "session_import": SessionImport,
    "manifest_requirements": ManifestRequirements,
    "session_list": SessionList,
    "session_close": SessionClose,
    "save": Save,
    "export_manifest": ExportManifest,
    "status": Status,
    "check": Check,
    "node_tree": NodeTree,
    "node_info": CommandNodeInfo,
    "node_add": NodeAdd,
    "node_set": NodeSet,
    "node_reparent": NodeReparent,
    "node_reorder": NodeReorder,
    "node_move": NodeMove,
    "node_duplicate": NodeDuplicate,
    "rename_id": RenameId,
    "mask_add": MaskAdd,
    "mask_set": MaskSet,
    "mask_reorder": MaskReorder,
    "mask_delete": MaskDelete,
    "physics_set": PhysicsSet,
    "physics_globals": PhysicsGlobals,
    "node_delete": NodeDelete,
    "texture_add": TextureAdd,
    "texture_list": TextureList,
    "param_add": ParamAdd,
    "param_list": ParamList,
    "param_set": ParamSet,
    "param_delete": ParamDelete,
    "param_key_insert": ParamKeyInsert,
    "param_key_delete": ParamKeyDelete,
    "param_key_move": ParamKeyMove,
    "param_flip": ParamFlip,
    "binding_add": BindingAdd,
    "binding_key": BindingKey,
    "binding_keys": BindingKeys,
    "binding_unset": BindingUnset,
    "binding_reset": BindingReset,
    "binding_delete": BindingDelete,
    "binding_interpolate": BindingInterpolate,
    "binding_invert": BindingInvert,
    "binding_copy_key": BindingCopyKey,
    "binding_list": BindingList,
    "deform_set": DeformSet,
    "deform_vertices": DeformVertices,
    "mesh_set": MeshSet,
    "mesh_auto": MeshAuto,
    "mesh_copy": MeshCopy,
    "seam_add": SeamAdd,
    "seam_delete": SeamDelete,
    "slot_add": SlotAdd,
    "slot_fill": SlotFill,
    "slot_clear": SlotClear,
    "slot_delete": SlotDelete,
    "seams": Seams,
    "welds": Welds,
    "unfilled_slots": UnfilledSlots,
    "weld_weight": WeldWeight,
    "weld_set": WeldSet,
    "weld_delete": WeldDelete,
    "physics_add": PhysicsAdd,
    "undo": Undo,
    "redo": Redo,
    "presence_set": PresenceSet,
    "presence_get": PresenceGet,
    "scratch_deform": ScratchDeform,
    "preview": Preview,
}


def parse_command(message: Mapping[str, Any]) -> Command:
    """One JSON object as the Command it is, by its "cmd" tag."""
    tag = message.get("cmd")
    found = COMMAND_VARIANTS.get(tag) if isinstance(tag, str) else None
    if found is None:
        raise ValueError(f"no Command carries the cmd {tag!r}")
    return _decode_class(found, message)


# What each command does to the document, keyed by its `cmd` tag. Written
# down once in Rust, in `COMMAND_KINDS`; a command missing from it fails the
# build rather than reaching a client unclassified.
COMMAND_KINDS: dict[str, CommandKind] = {
    "session_new": CommandKind.DOCUMENT,
    "session_open": CommandKind.DOCUMENT,
    "session_import": CommandKind.DOCUMENT,
    "manifest_requirements": CommandKind.SERVER_QUERY,
    "session_list": CommandKind.SERVER_QUERY,
    "session_close": CommandKind.DOCUMENT,
    "save": CommandKind.DOCUMENT,
    "export_manifest": CommandKind.SERVER_QUERY,
    "status": CommandKind.SERVER_QUERY,
    "check": CommandKind.REPLICA_QUERY,
    "node_tree": CommandKind.REPLICA_QUERY,
    "node_info": CommandKind.REPLICA_QUERY,
    "node_add": CommandKind.DOCUMENT,
    "node_set": CommandKind.DOCUMENT,
    "node_reparent": CommandKind.DOCUMENT,
    "node_reorder": CommandKind.DOCUMENT,
    "node_move": CommandKind.DOCUMENT,
    "node_duplicate": CommandKind.DOCUMENT,
    "rename_id": CommandKind.DOCUMENT,
    "mask_add": CommandKind.DOCUMENT,
    "mask_set": CommandKind.DOCUMENT,
    "mask_reorder": CommandKind.DOCUMENT,
    "mask_delete": CommandKind.DOCUMENT,
    "physics_set": CommandKind.DOCUMENT,
    "physics_globals": CommandKind.DOCUMENT,
    "node_delete": CommandKind.DOCUMENT,
    "texture_add": CommandKind.DOCUMENT,
    "texture_list": CommandKind.REPLICA_QUERY,
    "param_add": CommandKind.DOCUMENT,
    "param_list": CommandKind.REPLICA_QUERY,
    "param_set": CommandKind.DOCUMENT,
    "param_delete": CommandKind.DOCUMENT,
    "param_key_insert": CommandKind.DOCUMENT,
    "param_key_delete": CommandKind.DOCUMENT,
    "param_key_move": CommandKind.DOCUMENT,
    "param_flip": CommandKind.DOCUMENT,
    "binding_add": CommandKind.DOCUMENT,
    "binding_key": CommandKind.DOCUMENT,
    "binding_keys": CommandKind.DOCUMENT,
    "binding_unset": CommandKind.DOCUMENT,
    "binding_reset": CommandKind.DOCUMENT,
    "binding_delete": CommandKind.DOCUMENT,
    "binding_interpolate": CommandKind.DOCUMENT,
    "binding_invert": CommandKind.DOCUMENT,
    "binding_copy_key": CommandKind.DOCUMENT,
    "binding_list": CommandKind.REPLICA_QUERY,
    "deform_set": CommandKind.DOCUMENT,
    "deform_vertices": CommandKind.DOCUMENT,
    "mesh_set": CommandKind.DOCUMENT,
    "mesh_auto": CommandKind.DOCUMENT,
    "mesh_copy": CommandKind.DOCUMENT,
    "seam_add": CommandKind.DOCUMENT,
    "seam_delete": CommandKind.DOCUMENT,
    "slot_add": CommandKind.DOCUMENT,
    "slot_fill": CommandKind.DOCUMENT,
    "slot_clear": CommandKind.DOCUMENT,
    "slot_delete": CommandKind.DOCUMENT,
    "seams": CommandKind.REPLICA_QUERY,
    "welds": CommandKind.REPLICA_QUERY,
    "unfilled_slots": CommandKind.REPLICA_QUERY,
    "weld_weight": CommandKind.DOCUMENT,
    "weld_set": CommandKind.DOCUMENT,
    "weld_delete": CommandKind.DOCUMENT,
    "physics_add": CommandKind.DOCUMENT,
    "undo": CommandKind.DOCUMENT,
    "redo": CommandKind.DOCUMENT,
    "presence_set": CommandKind.PRESENCE,
    "presence_get": CommandKind.SERVER_QUERY,
    "scratch_deform": CommandKind.SCRATCH,
    "preview": CommandKind.SERVER_QUERY,
}

# A command that changes the document, or which documents exist.
#
# The session's revision moves, so every view of it re-reads. These are the
# commands that cost an undo entry and a React render, and the only ones
# that must reach the editor that owns the document.
DocumentCommand = (
    SessionNew
    | SessionOpen
    | SessionImport
    | SessionClose
    | Save
    | NodeAdd
    | NodeSet
    | NodeReparent
    | NodeReorder
    | NodeMove
    | NodeDuplicate
    | RenameId
    | MaskAdd
    | MaskSet
    | MaskReorder
    | MaskDelete
    | PhysicsSet
    | PhysicsGlobals
    | NodeDelete
    | TextureAdd
    | ParamAdd
    | ParamSet
    | ParamDelete
    | ParamKeyInsert
    | ParamKeyDelete
    | ParamKeyMove
    | ParamFlip
    | BindingAdd
    | BindingKey
    | BindingKeys
    | BindingUnset
    | BindingReset
    | BindingDelete
    | BindingInterpolate
    | BindingInvert
    | BindingCopyKey
    | DeformSet
    | DeformVertices
    | MeshSet
    | MeshAuto
    | MeshCopy
    | SeamAdd
    | SeamDelete
    | SlotAdd
    | SlotFill
    | SlotClear
    | SlotDelete
    | WeldWeight
    | WeldSet
    | WeldDelete
    | PhysicsAdd
    | Undo
    | Redo
)

# A command that publishes shared view state: pose, camera, selection.
#
# It goes to the editor because other clients read it back, and it changes no
# document: no revision, no undo entry, invisible to a panel.
PresenceCommand = PresenceSet

# A command that shows a live edit on a puppet without authoring it.
#
# The drag path. Whoever owns the puppet being drawn serves it — a client
# with a local replica serves its own, and never asks the editor. A gesture
# of any length repaints the canvas and re-renders nothing.
ScratchCommand = ScratchDeform

# A read that is a pure function of the model.
#
# A client holding a replica answers it locally, with no round trip. The
# editor answers it the same way, from the same bytes.
ReplicaQueryCommand = (
    Check
    | NodeTree
    | CommandNodeInfo
    | TextureList
    | ParamList
    | BindingList
    | Seams
    | Welds
    | UnfilledSlots
)

# A read that needs the editor itself: its session bookkeeping, its store or
# its renderer.
#
# A replica cannot answer one, so these always go over the wire.
ServerQueryCommand = (
    ManifestRequirements
    | SessionList
    | ExportManifest
    | Status
    | PresenceGet
    | Preview
)

# A command that reads, whoever answers it.
#
# The union of the two query kinds, for a caller that only cares that nothing
# changed. A client routes on the halves; a caller sends either.
QueryCommand = ReplicaQueryCommand | ServerQueryCommand


class NodeKindArg(StrEnum):
    GROUP = "group"
    PART = "part"
    COMPOSITE = "composite"
    MESH_GROUP = "mesh_group"


class NodeKind(StrEnum):
    """What a node is, as a reply reports it. [`NodeKindArg`] is the add side and
    carries no `Physics`: [`Command::PhysicsAdd`] is what makes one.
    """

    GROUP = "group"
    PART = "part"
    COMPOSITE = "composite"
    MESH_GROUP = "mesh_group"
    PHYSICS = "physics"


class MaskMode(StrEnum):
    """What a mask source does to the drawable it is attached to."""

    MASK = "mask"
    DODGE = "dodge"


class PhysicsKind(StrEnum):
    """The pendulum a physics driver swings."""

    RIGID = "rigid"
    SPRING = "spring"


class PhysicsMapMode(StrEnum):
    """What a physics driver's two outputs mean; see [`PhysicsTargets`]."""

    XY = "xy"
    YX = "yx"
    ANGLE_LENGTH = "angle_length"
    LENGTH_ANGLE = "length_angle"


class Interpolate(StrEnum):
    """How a binding reads between the cells its author keyed."""

    NEAREST = "nearest"
    STEPPED = "stepped"
    LINEAR = "linear"
    CUBIC = "cubic"


class BlendMode(StrEnum):
    """How a drawable composites onto what is already under it."""

    NORMAL = "normal"
    MULTIPLY = "multiply"
    COLOR_DODGE = "color_dodge"
    LINEAR_DODGE = "linear_dodge"
    SCREEN = "screen"
    CLIP_TO_LOWER = "clip_to_lower"
    SLICE_FROM_LOWER = "slice_from_lower"
    OVERLAY = "overlay"
    COLOR_BURN = "color_burn"
    LINEAR_BURN = "linear_burn"
    DARKEN = "darken"
    LIGHTEN = "lighten"
    ADD = "add"
    INVERSE = "inverse"
    SUBTRACT = "subtract"


class ScalarTarget(StrEnum):
    """A property a binding drives with one number per cell.

    The spellings are the model file's own, which is why the colour and
    output-scale channels run their words together rather than reading as
    snake_case.
    """

    TX = "tx"
    TY = "ty"
    SX = "sx"
    SY = "sy"
    RX = "rx"
    RY = "ry"
    RZ = "rz"
    Z_ORDER = "z_order"
    OPACITY = "opacity"
    TINTR = "tintr"
    TINTG = "tintg"
    TINTB = "tintb"
    SCREENTINTR = "screentintr"
    SCREENTINTG = "screentintg"
    SCREENTINTB = "screentintb"
    OUTPUTSCALEX = "outputscalex"
    OUTPUTSCALEY = "outputscaley"


class BindingTarget(StrEnum):
    """Any property a binding drives: one of [`ScalarTarget`]'s scalars, or the
    per-vertex deform, which the deform commands author instead.
    """

    TX = "tx"
    TY = "ty"
    SX = "sx"
    SY = "sy"
    RX = "rx"
    RY = "ry"
    RZ = "rz"
    Z_ORDER = "z_order"
    OPACITY = "opacity"
    TINTR = "tintr"
    TINTG = "tintg"
    TINTB = "tintb"
    SCREENTINTR = "screentintr"
    SCREENTINTG = "screentintg"
    SCREENTINTB = "screentintb"
    OUTPUTSCALEX = "outputscalex"
    OUTPUTSCALEY = "outputscaley"
    DEFORM = "deform"


@dataclass(frozen=True, kw_only=True)
class NodePatch:
    """Fields to change on a node; every field is optional (absent = unchanged).
    Kind-specific fields are ignored on nodes of another kind: the colour fields
    (`opacity`, `blend_mode`, `tint`, `screen_tint`) reach parts and composites
    only, because a mesh group is never drawn and carries no colour.
    """

    # The label a person reads. Free to repeat; nothing is addressed by it.
    name: str | None = None
    translate: tuple[float, float, float] | None = None
    rotate: tuple[float, float, float] | None = None
    scale: tuple[float, float] | None = None
    z_order: float | None = None
    opacity: float | None = None
    enabled: bool | None = None
    # The texture the part draws, in three states: absent leaves it as it
    # is, `null` draws none, an Id draws that one. Ignored on a node that is
    # not a part. Dropping the last part drawing a texture takes the texture
    # with it — see [`ResponseBody::Node::dropped`].
    texture: TexId | Clear | None = None
    lock_to_root: bool | None = None
    blend_mode: BlendMode | None = None
    tint: tuple[float, float, float] | None = None
    screen_tint: tuple[float, float, float] | None = None
    mask_threshold: float | None = None
    # Composite: forward mesh-group deformation to children.
    propagate_meshgroup: bool | None = None
    mg_dynamic: bool | None = None
    mg_translate_children: bool | None = None


@dataclass(frozen=True, kw_only=True)
class PhysicsTargets:
    """The params a physics driver writes, one field per output.

    A driver has exactly two outputs and never a third, so this is a struct
    rather than a list: there is no way to name an output that does not exist,
    and no positional hole to spell with a `null`. An absent field is an output
    bound to nothing, so `{"length": "len"}` is a driver whose second output
    drives a param and whose first drives none, and `{}` is a driver that
    writes nothing.

    The names are the outputs under the `angle_length` map mode. Another map
    mode changes what each output *means* — `length_angle` swaps them, `xy` and
    `yx` make them a position — never how many there are.
    """

    # The param the driver's first output writes.
    angle: ParamId | None = None
    # The param the driver's second output writes.
    length: ParamId | None = None


@dataclass(frozen=True, kw_only=True)
class AutoMeshContour:
    """Trace the alpha contours: one pinned boundary loop per connected
    component, plus the free interior vertices `rings` and `spacing` ask
    for.
    """

    TAG_FIELD: ClassVar[str] = "mode"
    TAG: ClassVar[str] = "contour"

    # Alpha strictly above this counts as solid.
    threshold: int | None = None
    # Douglas-Peucker tolerance, in texels: higher is a coarser outline.
    simplify: float | None = None
    # Texels of outward dilation before tracing, so the outline clears
    # the art's own edge.
    margin: int | None = None
    # Interior fill-point spacing in texels; 0 is boundary only.
    spacing: int | None = None
    # One ring of free vertices per factor, the traced outline scaled
    # about its own centroid: 0 is the centroid itself, 1 the outline.
    # A factor above 1 is clamped to 1 — `margin` already dilates the
    # mask before tracing, and a vertex outside the pinned loop would
    # only make triangles the alpha cull drops. Empty places no rings,
    # which is the default.
    rings: list[float] | None = None
    # Texels: a free vertex closer than this to one already placed is
    # dropped, so rings and fill do not crowd the outline. The pinned
    # outline itself is never thinned.
    min_distance: float | None = None
    # Texel x of a vertical mirror line: free vertices are generated
    # from `x <= mirror_x` and reflected across it, so a symmetric part
    # gets a symmetric interior. The outline is traced from the alpha
    # and is not mirrored.
    mirror_x: float | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class AutoMeshGrid:
    """A grid over the bounding box of the solid texels."""

    TAG_FIELD: ClassVar[str] = "mode"
    TAG: ClassVar[str] = "grid"

    # Alpha strictly above this counts as solid, and is what the
    # bounding box is measured from.
    threshold: int | None = None
    cols: int | None = None
    rows: int | None = None
    # Grid lines as fractions of the solid bounding box — 0 its left
    # edge, 1 its right — so the grid need not be uniform. Values
    # outside `0..=1` put a line outside the box. Present, it replaces
    # both `cols` and `margin` on this axis. A grid is mirrored by
    # asking for symmetric fractions, which is why there is no mirror
    # knob here.
    axes_x: list[float] | None = None
    # The same, down, replacing `rows`.
    axes_y: list[float] | None = None
    # Fraction of the bounding box added outside it on both sides, when
    # the lines come from `cols`/`rows`.
    margin: float | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


# How [`Command::MeshAuto`] derives a mesh from a part's alpha.
#
# **Every knob is optional, and none of the defaults are written here.** They
# live in `catchlight-editor-core` beside the code that reads them, so the
# wire cannot drift from what the editor actually does; absent means "what
# the editor would have used". `{"mode": "contour"}` is the default trace.
AutoMesh = (
    AutoMeshContour
    | AutoMeshGrid
)

AUTO_MESH_VARIANTS: dict[str, type[AutoMesh]] = {
    "contour": AutoMeshContour,
    "grid": AutoMeshGrid,
}


def parse_auto_mesh(message: Mapping[str, Any]) -> AutoMesh:
    """One JSON object as the AutoMesh it is, by its "mode" tag."""
    tag = message.get("mode")
    found = AUTO_MESH_VARIANTS.get(tag) if isinstance(tag, str) else None
    if found is None:
        raise ValueError(f"no AutoMesh carries the mode {tag!r}")
    return _decode_class(found, message)


@dataclass(frozen=True, kw_only=True)
class RenameNode:
    TAG_FIELD: ClassVar[str] = "kind"
    TAG: ClassVar[str] = "node"
    WIRE: ClassVar[Mapping[str, str]] = {
        "from_": "from",
    }

    from_: NodeId
    to: NodeId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class RenameParam:
    TAG_FIELD: ClassVar[str] = "kind"
    TAG: ClassVar[str] = "param"
    WIRE: ClassVar[Mapping[str, str]] = {
        "from_": "from",
    }

    from_: ParamId
    to: ParamId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class RenameTexture:
    TAG_FIELD: ClassVar[str] = "kind"
    TAG: ClassVar[str] = "texture"
    WIRE: ClassVar[Mapping[str, str]] = {
        "from_": "from",
    }

    from_: TexId
    to: TexId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class RenameSeam:
    """A seam is scoped to its part, so this one names the part too. Every
    weld that ended on the old Id follows it.
    """

    TAG_FIELD: ClassVar[str] = "kind"
    TAG: ClassVar[str] = "seam"
    WIRE: ClassVar[Mapping[str, str]] = {
        "from_": "from",
    }

    node: NodeId
    from_: SeamId
    to: SeamId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


# Which Id [`Command::RenameId`] changes, and to what.
Rename = (
    RenameNode
    | RenameParam
    | RenameTexture
    | RenameSeam
)

RENAME_VARIANTS: dict[str, type[Rename]] = {
    "node": RenameNode,
    "param": RenameParam,
    "texture": RenameTexture,
    "seam": RenameSeam,
}


def parse_rename(message: Mapping[str, Any]) -> Rename:
    """One JSON object as the Rename it is, by its "kind" tag."""
    tag = message.get("kind")
    found = RENAME_VARIANTS.get(tag) if isinstance(tag, str) else None
    if found is None:
        raise ValueError(f"no Rename carries the kind {tag!r}")
    return _decode_class(found, message)


@dataclass(frozen=True, kw_only=True)
class BindingParams:
    """The param, or the pair of params, a binding is keyed by. With `param_y`
    the binding's grid spans both params' key positions and `cell` indexes
    both; without it the grid is one row and `cell[1]` is 0.
    """

    param: ParamId
    param_y: ParamId | None = None


@dataclass(frozen=True, kw_only=True)
class BindingKeyEntry:
    target: ScalarTarget
    value: float


@dataclass(frozen=True, kw_only=True)
class ParamPose:
    """One param at one value — a pose is a list of these. Params are scalar, so
    there is one number.
    """

    param: ParamId
    value: float


@dataclass(frozen=True, kw_only=True)
class SeamAddr:
    """One end of a weld: the seam, and the part carrying it."""

    node: NodeId
    seam: SeamId


@dataclass(frozen=True, kw_only=True)
class SlotAddr:
    """One slot of a model, named in full."""

    node: NodeId
    seam: SeamId
    slot: SlotId


@dataclass(frozen=True, kw_only=True)
class SeamSlot:
    """One slot of a part's seam — the part is whatever carries the reply."""

    seam: SeamId
    slot: SlotId


@dataclass(frozen=True, kw_only=True)
class SlotWeight:
    """A slot's share of the point its two welded vertices are pulled toward."""

    slot: SlotId
    weight: float


@dataclass(frozen=True, kw_only=True)
class Presence:
    """Ephemeral shared view state. Rides its own path — decoupled from the document
    so scrubbing/panning generate zero document traffic and never persist.
    """

    pose: list[ParamPose] = field(default_factory=list)
    camera: Camera | None = None
    selection: NodeId | None = None


@dataclass(frozen=True, kw_only=True)
class Camera:
    center: tuple[float, float]
    height: float


@dataclass(frozen=True, kw_only=True)
class ReplyOk:
    TAG_FIELD: ClassVar[str] = "reply"
    TAG: ClassVar[str] = "ok"

    id: int
    # The addressed session's revision *after* this command, so a client
    # knows what its reply describes without a second round trip.
    #
    # Present whenever the command named a session — including one it
    # only read, and including the create/open/import commands, which
    # report the revision of the session they just made. Absent for the
    # editor-level commands that name no session at all, and for a
    # `session_close`, whose session is gone.
    rev: int | None = None
    body: ResponseBody

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ReplyErr:
    """`code` is what a client branches on; `message` is for a person."""

    TAG_FIELD: ClassVar[str] = "reply"
    TAG: ClassVar[str] = "err"

    id: int
    code: ErrorCode
    message: str

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ReplyEvent:
    TAG_FIELD: ClassVar[str] = "reply"
    TAG: ClassVar[str] = "event"
    FLATTEN: ClassVar[tuple[str, ...]] = ("event",)

    event: Event

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


# The server's answer. `Ok`/`Err` carry the request's `id`; `Event` is
# unsolicited (a document changed on a session this client observes).
Reply = (
    ReplyOk
    | ReplyErr
    | ReplyEvent
)

REPLY_VARIANTS: dict[str, type[Reply]] = {
    "ok": ReplyOk,
    "err": ReplyErr,
    "event": ReplyEvent,
}


def parse_reply(message: Mapping[str, Any]) -> Reply:
    """One JSON object as the Reply it is, by its "reply" tag."""
    tag = message.get("reply")
    found = REPLY_VARIANTS.get(tag) if isinstance(tag, str) else None
    if found is None:
        raise ValueError(f"no Reply carries the reply {tag!r}")
    return _decode_class(found, message)


class ErrorCode(StrEnum):
    """Why a command was refused. A client that has to react — a commit gate
    waiting on unfilled slots, a mesh editor offering to refill a seam —
    branches on this rather than on the message text.
    """

    # No open session with that [`SessionId`].
    NO_SESSION = "no_session"
    # The model carries no node with that [`NodeId`].
    NO_NODE = "no_node"
    # The model carries no param with that [`ParamId`].
    NO_PARAM = "no_param"
    # The model carries no texture with that [`TexId`].
    NO_TEXTURE = "no_texture"
    # The request did not parse: bad JSON, an unknown command, or a string
    # that is not a valid Id.
    BAD_REQUEST = "bad_request"
    # A target that does not fit the thing it names: a physics field on a
    # node that is not a driver, a `deform` where only a scalar can go. A
    # *misspelled* one never gets this far — it is [`Self::BadRequest`].
    BAD_TARGET = "bad_target"
    NOTHING_TO_UNDO = "nothing_to_undo"
    NOTHING_TO_REDO = "nothing_to_redo"
    # A save with no path, on a session that has no file of its own.
    NO_SAVE_PATH = "no_save_path"
    # The part carries no such seam.
    UNKNOWN_SEAM = "unknown_seam"
    # The seam carries no such slot.
    UNKNOWN_SLOT = "unknown_slot"
    # An add named an Id the model already carries.
    DUPLICATE_ID = "duplicate_id"
    # The part already carries a seam with that Id.
    DUPLICATE_SEAM = "duplicate_seam"
    # The seam already holds a slot with that Id.
    DUPLICATE_SLOT = "duplicate_slot"
    # A weld's two seams must hold the same slots, each weighted once.
    WELD_SLOT_MISMATCH = "weld_slot_mismatch"
    # No weld pairs the two seams named.
    UNKNOWN_WELD = "unknown_weld"
    # The texture carries no pixel above the alpha threshold, so there is no
    # shape to mesh. A client offers a lower threshold rather than an error.
    NOTHING_TO_MESH = "nothing_to_mesh"
    # This needs a complete model and the session holds an addon fragment.
    # A session never opens one, so nothing should see this today.
    FRAGMENT = "fragment"
    # The model refused the edit for some other reason; read `message`.
    EDIT = "edit"
    # A manifest could not be read or written.
    MANIFEST = "manifest"
    IO = "io"
    # An image could not be decoded.
    IMAGE = "image"
    # The preview renderer failed.
    PREVIEW = "preview"
    # The command needs a filesystem or a GPU and this build has neither
    # (wasm).
    NATIVE_ONLY = "native_only"


@dataclass(frozen=True, kw_only=True)
class ResponseBodyEmpty:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "empty"

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodySession:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "session"

    session: SessionId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodySessions:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "sessions"

    sessions: list[SessionInfo]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyNode:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "node"

    node: NodeId
    # Textures the edit deleted, because no part draws them any more.
    # Every texture a model carries is drawn by a part, so repointing or
    # removing the last one takes the texture with it.
    dropped: list[TexId] = field(default_factory=list)

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyParam:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "param"

    param: ParamId

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodySeam:
    """One seam, named in full: what [`Command::SeamAdd`] answers with, so a
    client that let the editor draw the Id learns which one it drew.
    """

    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "seam"

    seam: SeamAddr

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodySlot:
    """One slot, named in full, for the same reason."""

    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "slot"

    slot: SlotAddr

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyParams:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "params"

    params: list[ParamInfo]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyBindings:
    """Every binding on one node, in the order the model holds them."""

    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "bindings"

    bindings: list[BindingInfo]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyTexture:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "texture"

    texture: TexId
    # Textures the edit deleted, because the part that had been drawing
    # them stopped and nothing else was. Every texture a model carries
    # is drawn by a part, so an upload that displaces the last user of
    # the old one takes it.
    dropped: list[TexId] = field(default_factory=list)

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyTextures:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "textures"

    textures: list[TexInfo]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyTree:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "tree"

    root: TreeNode

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyNodeInfo:
    """One node in full, as an inspector shows it. Boxed because it is far
    the largest thing a reply carries, and every other reply would pay for
    it in [`Reply`]'s size.
    """

    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "node_info"

    node: NodeInfo

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyStatus:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "status"

    status: StatusInfo

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyWarnings:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "warnings"

    warnings: list[str]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyPreview:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "preview"

    preview: PreviewInfo

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodySaved:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "saved"

    path: str

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyPresence:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "presence"

    presence: Presence | None = None

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodySeams:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "seams"

    seams: list[SeamInfo]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyWelds:
    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "welds"

    welds: list[WeldInfo]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyUnfilledSlots:
    """Slots nothing fills, across the whole model."""

    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "unfilled_slots"

    slots: list[SlotAddr]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyEmptied:
    """The slots a mesh edit emptied on `node`, in seam-then-slot order."""

    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "emptied"

    node: NodeId
    slots: list[SeamSlot]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class ResponseBodyManifestRequirements:
    """Storage keys an import needs, already resolved against the manifest's
    own key — so a client stages them verbatim.
    """

    TAG_FIELD: ClassVar[str] = "result"
    TAG: ClassVar[str] = "manifest_requirements"

    textures: list[str]

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


ResponseBody = (
    ResponseBodyEmpty
    | ResponseBodySession
    | ResponseBodySessions
    | ResponseBodyNode
    | ResponseBodyParam
    | ResponseBodySeam
    | ResponseBodySlot
    | ResponseBodyParams
    | ResponseBodyBindings
    | ResponseBodyTexture
    | ResponseBodyTextures
    | ResponseBodyTree
    | ResponseBodyNodeInfo
    | ResponseBodyStatus
    | ResponseBodyWarnings
    | ResponseBodyPreview
    | ResponseBodySaved
    | ResponseBodyPresence
    | ResponseBodySeams
    | ResponseBodyWelds
    | ResponseBodyUnfilledSlots
    | ResponseBodyEmptied
    | ResponseBodyManifestRequirements
)

RESPONSE_BODY_VARIANTS: dict[str, type[ResponseBody]] = {
    "empty": ResponseBodyEmpty,
    "session": ResponseBodySession,
    "sessions": ResponseBodySessions,
    "node": ResponseBodyNode,
    "param": ResponseBodyParam,
    "seam": ResponseBodySeam,
    "slot": ResponseBodySlot,
    "params": ResponseBodyParams,
    "bindings": ResponseBodyBindings,
    "texture": ResponseBodyTexture,
    "textures": ResponseBodyTextures,
    "tree": ResponseBodyTree,
    "node_info": ResponseBodyNodeInfo,
    "status": ResponseBodyStatus,
    "warnings": ResponseBodyWarnings,
    "preview": ResponseBodyPreview,
    "saved": ResponseBodySaved,
    "presence": ResponseBodyPresence,
    "seams": ResponseBodySeams,
    "welds": ResponseBodyWelds,
    "unfilled_slots": ResponseBodyUnfilledSlots,
    "emptied": ResponseBodyEmptied,
    "manifest_requirements": ResponseBodyManifestRequirements,
}


def parse_response_body(message: Mapping[str, Any]) -> ResponseBody:
    """One JSON object as the ResponseBody it is, by its "result" tag."""
    tag = message.get("result")
    found = RESPONSE_BODY_VARIANTS.get(tag) if isinstance(tag, str) else None
    if found is None:
        raise ValueError(f"no ResponseBody carries the result {tag!r}")
    return _decode_class(found, message)


@dataclass(frozen=True, kw_only=True)
class EventDocumentChanged:
    """The document changed; `rev` is the session's new revision. Observers
    re-read when their last-seen rev is older.
    """

    TAG_FIELD: ClassVar[str] = "event"
    TAG: ClassVar[str] = "document_changed"

    session: SessionId
    rev: int

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


@dataclass(frozen=True, kw_only=True)
class EventSessionsChanged:
    """The set of open sessions changed: one was created, opened, imported or
    closed. Carries nothing — an observer that cares re-reads
    [`Command::SessionList`], which is the only answer that is not already
    stale by the time it arrives.
    """

    TAG_FIELD: ClassVar[str] = "event"
    TAG: ClassVar[str] = "sessions_changed"

    def to_wire(self) -> dict[str, Any]:
        """This value, as one JSON object: its tag, then every field it set."""
        return _wire_fields(self)


Event = (
    EventDocumentChanged
    | EventSessionsChanged
)

EVENT_VARIANTS: dict[str, type[Event]] = {
    "document_changed": EventDocumentChanged,
    "sessions_changed": EventSessionsChanged,
}


def parse_event(message: Mapping[str, Any]) -> Event:
    """One JSON object as the Event it is, by its "event" tag."""
    tag = message.get("event")
    found = EVENT_VARIANTS.get(tag) if isinstance(tag, str) else None
    if found is None:
        raise ValueError(f"no Event carries the event {tag!r}")
    return _decode_class(found, message)


@dataclass(frozen=True, kw_only=True)
class SessionInfo:
    session: SessionId
    title: str
    file: str | None = None
    dirty: bool
    rev: int
    node_count: int


@dataclass(frozen=True, kw_only=True)
class StatusInfo:
    title: str
    node_count: int
    param_count: int
    texture_count: int
    dirty: bool
    rev: int


@dataclass(frozen=True, kw_only=True)
class TreeNode:
    # What the node is addressed by, here and in the file.
    id: NodeId
    # What a person reads. Free to repeat.
    name: str
    kind: NodeKind
    z_order: float
    enabled: bool = True
    children: list[TreeNode]


@dataclass(frozen=True, kw_only=True)
class NodeInfo:
    """One node in full: what [`NodePatch`] can set, plus what it cannot — the
    node's Id, its kind, its parent, and the size of the mesh it holds.

    **The settable fields carry [`NodePatch`]'s own names.** An inspector reads
    a value here, edits it, and sends it straight back in a
    [`Command::NodeSet`] under the same key; a field that spelled itself
    differently on the way out would be a rename nothing checks.

    A field a node's kind does not carry is absent, the way it is ignored on
    the way in: the colour fields reach parts and composites only, `texture`
    only a part, `mg_*` only a mesh group, and the two mesh counts only the
    kinds that hold a mesh. `texture` is also absent on a part that draws
    none, which `kind` tells apart from a node that could not have one — a
    reply has nothing to undo, so it never carries the `null` a patch spells
    "draw none" with.
    """

    # What the node is addressed by, here and in the file.
    id: NodeId
    # The same kind [`TreeNode::kind`] carries.
    kind: NodeKind
    # Absent on the root, which is the one node with no parent.
    parent: NodeId | None = None
    # What a person reads. Free to repeat; nothing is addressed by it.
    name: str
    translate: tuple[float, float, float]
    rotate: tuple[float, float, float]
    scale: tuple[float, float]
    z_order: float
    enabled: bool
    lock_to_root: bool
    opacity: float | None = None
    blend_mode: BlendMode | None = None
    tint: tuple[float, float, float] | None = None
    screen_tint: tuple[float, float, float] | None = None
    mask_threshold: float | None = None
    # The part's albedo texture, absent when it draws none.
    texture: TexId | None = None
    # How many vertices the node's mesh holds. Absent on a kind that carries
    # no mesh — a part and a mesh group carry one, nothing else does — so
    # `0` is a mesh with no vertices rather than a node that could not have
    # had any. A client asking "has this part been meshed" reads this rather
    # than [`Command::Check`], whose textured-but-untriangulated warning is a
    # message for a person.
    vertex_count: int | None = None
    # How many triangles that mesh holds, absent under the same rule.
    triangle_count: int | None = None
    # Composite: forward mesh-group deformation to children.
    propagate_meshgroup: bool | None = None
    mg_dynamic: bool | None = None
    mg_translate_children: bool | None = None


@dataclass(frozen=True, kw_only=True)
class TexInfo:
    id: TexId
    width: int
    height: int


@dataclass(frozen=True, kw_only=True)
class ParamInfo:
    # What the param is addressed by.
    id: ParamId
    # What a person reads. Free to repeat.
    name: str
    min: float
    max: float
    default: float = 0.0
    # Key positions, normalized 0..1 across `[min, max]`. Always at least
    # the two endpoints, so a binding's grid is `key_positions.len()` wide.
    key_positions: list[float] = field(default_factory=list)
    bindings: int


@dataclass(frozen=True, kw_only=True)
class BindingInfo:
    """One binding, as a panel draws it: the params driving it, the property it
    drives, how it reads between cells, and the grid the author keyed.

    **The grid is `[y][x]`** — the transpose of the `cell: [x, y]` every
    binding command takes, so `keys[cell[1]][cell[0]]` is the cell
    [`Command::BindingKey`] would write. It is the full product of the params'
    key positions, [`Self::width`] by [`Self::height`], with one row when
    there is no `param_y`.

    **A `null` in `keys` is a cell nobody authored.** The model stores only the
    cells a rigger set and derives the rest at puppet build, and "unset" is a
    state they act on — it is not a zero. The exception is a `deform` binding,
    which authors per-vertex offsets rather than one number: every one of its
    cells reads `null` here and [`Self::authored`] is the only thing that says
    which are set. For every other target `authored[y][x]` is exactly
    `keys[y][x] != null`.
    """

    # The property driven — plus `deform`, which only the deform commands
    # author.
    target: BindingTarget
    # The param along the grid's x axis.
    param: ParamId
    # The param along the grid's y axis. Absent when the grid is one row.
    param_y: ParamId | None = None
    # How it reads between cells, as [`Command::BindingInterpolate`] takes
    # it back.
    interpolate: Interpolate
    # How many key positions `param` has, so how wide the grid is.
    width: int
    # How many key positions `param_y` has, or 1.
    height: int
    # The authored value at each cell, `[y][x]`, `null` where nothing was
    # authored.
    keys: list[list[float | None]]
    # Whether each cell was authored at all, `[y][x]`.
    authored: list[list[bool]]


@dataclass(frozen=True, kw_only=True)
class SeamInfo:
    """A seam and what currently fills it."""

    id: SeamId
    slots: list[SlotInfo]


@dataclass(frozen=True, kw_only=True)
class SlotInfo:
    """One slot; `vertex` absent means unfilled, and welds skip it."""

    id: SlotId
    vertex: int | None = None


@dataclass(frozen=True, kw_only=True)
class WeldInfo:
    a: SeamAddr
    b: SeamAddr
    weights: list[SlotWeight]


@dataclass(frozen=True, kw_only=True)
class PreviewInfo:
    path: str
    width: int
    height: int

__all__ = [
    "Clear",
    "CLEAR",
    "CommandKind",
    "SessionId",
    "NodeId",
    "ParamId",
    "TexId",
    "SeamId",
    "SlotId",
    "SessionNew",
    "SessionOpen",
    "SessionImport",
    "ManifestRequirements",
    "SessionList",
    "SessionClose",
    "Save",
    "ExportManifest",
    "Status",
    "Check",
    "NodeTree",
    "CommandNodeInfo",
    "NodeAdd",
    "NodeSet",
    "NodeReparent",
    "NodeReorder",
    "NodeMove",
    "NodeDuplicate",
    "RenameId",
    "MaskAdd",
    "MaskSet",
    "MaskReorder",
    "MaskDelete",
    "PhysicsSet",
    "PhysicsGlobals",
    "NodeDelete",
    "TextureAdd",
    "TextureList",
    "ParamAdd",
    "ParamList",
    "ParamSet",
    "ParamDelete",
    "ParamKeyInsert",
    "ParamKeyDelete",
    "ParamKeyMove",
    "ParamFlip",
    "BindingAdd",
    "BindingKey",
    "BindingKeys",
    "BindingUnset",
    "BindingReset",
    "BindingDelete",
    "BindingInterpolate",
    "BindingInvert",
    "BindingCopyKey",
    "BindingList",
    "DeformSet",
    "DeformVertices",
    "MeshSet",
    "MeshAuto",
    "MeshCopy",
    "SeamAdd",
    "SeamDelete",
    "SlotAdd",
    "SlotFill",
    "SlotClear",
    "SlotDelete",
    "Seams",
    "Welds",
    "UnfilledSlots",
    "WeldWeight",
    "WeldSet",
    "WeldDelete",
    "PhysicsAdd",
    "Undo",
    "Redo",
    "PresenceSet",
    "PresenceGet",
    "ScratchDeform",
    "Preview",
    "Command",
    "COMMAND_VARIANTS",
    "parse_command",
    "COMMAND_KINDS",
    "DocumentCommand",
    "PresenceCommand",
    "ScratchCommand",
    "ReplicaQueryCommand",
    "ServerQueryCommand",
    "QueryCommand",
    "NodeKindArg",
    "NodeKind",
    "MaskMode",
    "PhysicsKind",
    "PhysicsMapMode",
    "Interpolate",
    "BlendMode",
    "ScalarTarget",
    "BindingTarget",
    "NodePatch",
    "PhysicsTargets",
    "AutoMeshContour",
    "AutoMeshGrid",
    "AutoMesh",
    "AUTO_MESH_VARIANTS",
    "parse_auto_mesh",
    "RenameNode",
    "RenameParam",
    "RenameTexture",
    "RenameSeam",
    "Rename",
    "RENAME_VARIANTS",
    "parse_rename",
    "BindingParams",
    "BindingKeyEntry",
    "ParamPose",
    "SeamAddr",
    "SlotAddr",
    "SeamSlot",
    "SlotWeight",
    "Presence",
    "Camera",
    "ReplyOk",
    "ReplyErr",
    "ReplyEvent",
    "Reply",
    "REPLY_VARIANTS",
    "parse_reply",
    "ErrorCode",
    "ResponseBodyEmpty",
    "ResponseBodySession",
    "ResponseBodySessions",
    "ResponseBodyNode",
    "ResponseBodyParam",
    "ResponseBodySeam",
    "ResponseBodySlot",
    "ResponseBodyParams",
    "ResponseBodyBindings",
    "ResponseBodyTexture",
    "ResponseBodyTextures",
    "ResponseBodyTree",
    "ResponseBodyNodeInfo",
    "ResponseBodyStatus",
    "ResponseBodyWarnings",
    "ResponseBodyPreview",
    "ResponseBodySaved",
    "ResponseBodyPresence",
    "ResponseBodySeams",
    "ResponseBodyWelds",
    "ResponseBodyUnfilledSlots",
    "ResponseBodyEmptied",
    "ResponseBodyManifestRequirements",
    "ResponseBody",
    "RESPONSE_BODY_VARIANTS",
    "parse_response_body",
    "EventDocumentChanged",
    "EventSessionsChanged",
    "Event",
    "EVENT_VARIANTS",
    "parse_event",
    "SessionInfo",
    "StatusInfo",
    "TreeNode",
    "NodeInfo",
    "TexInfo",
    "ParamInfo",
    "BindingInfo",
    "SeamInfo",
    "SlotInfo",
    "WeldInfo",
    "PreviewInfo",
]
